import test from 'node:test';
import assert from 'node:assert/strict';
import {newCrawl,crawlStep,finished,crawlReport,enqueue} from '../lib/site-crawl.ts';
const html=(title,links='')=>`<title>${title}</title><meta name="description" content="Shared description"><h1>${title}</h1>${links}`;
test('full crawler exceeds ten pages, follows sitemap indexes, respects scope and resumes serialized state',async()=>{
 const original=globalThis.fetch,seen=[];globalThis.fetch=async input=>{const url=String(input);seen.push(url);if(url.includes('dns-query'))return Response.json({Answer:[{type:1,data:'93.184.215.14'}]});if(url.endsWith('/robots.txt'))return new Response('User-agent: *\nDisallow: /private\nSitemap: https://public.com/index.xml');if(url.endsWith('/sitemap.xml'))return new Response('',{status:404});if(url.endsWith('/index.xml'))return new Response('<sitemapindex><sitemap><loc>https://public.com/pages.xml</loc></sitemap></sitemapindex>');if(url.endsWith('/pages.xml'))return new Response('<urlset>'+Array.from({length:12},(_,i)=>`<url><loc>https://public.com/page${i}</loc></url>`).join('')+'</urlset>');return new Response(html(url,'<a href="/private">Private</a><a href="https://other.com/x">Other</a><a href="/page0?sort=x">Query</a><a href="/page0#heading">Same</a>'),{headers:{'content-type':'text/html'}})};
 try{let s=newCrawl('https://public.com',100);while(!finished(s)){s=await crawlStep(JSON.parse(JSON.stringify(s)))}assert.equal(s.pages.length,13);assert.ok(!seen.some(u=>u.includes('/private')||u.includes('other.com')||u.includes('?sort')));assert.ok(s.blocked>0);const report=crawlReport(s);assert.ok(report.coverage.includes('discovered crawlable URLs checked'));assert.ok(report.issues.some(i=>i.title==='Review duplicate meta descriptions'));}finally{globalThis.fetch=original}
});
test('crawl limit explicitly produces partial coverage and strips fragments',()=>{const s=newCrawl('https://public.com',10);s.initialized=true;s.pages=Array(10).fill({url:'https://public.com',error:'failed',status:0});enqueue(s,'/next#one',1);enqueue(s,'/next#two',1);assert.equal(s.pending.length,1);assert.equal(finished(s),true);assert.match(crawlReport(s).coverage,/partial crawl/)});
test('robots fetch failure and private DNS stop safely before page retrieval',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({Answer:[{type:1,data:'127.0.0.1'}]});await assert.rejects(()=>crawlStep(newCrawl('https://public.com',100)),/public internet/);globalThis.fetch=async input=>String(input).includes('dns-query')?Response.json({Answer:[{type:1,data:'93.184.215.14'}]}):new Response('',{status:503});await assert.rejects(()=>crawlStep(newCrawl('https://public.com',100)),/Robots policy/);}finally{globalThis.fetch=original}});
