import {db,fail,body,HttpError} from '@/lib/server';
import {connection,google} from '@/lib/google-analytics-server';
import {searchDates} from '@/lib/analytics-dashboard-data';
async function sites(token:string){const d=await google('https://www.googleapis.com/webmasters/v3/sites',token);return (d.siteEntry||[]).filter((s:any)=>s.permissionLevel!=='siteUnverifiedUser')}
function shift(date:string,days:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export async function GET(request:Request){try{const {row,user,projectId}=await connection(request),q=new URL(request.url).searchParams;const saved=await db().prepare('SELECT site_url FROM google_search_sites WHERE user_id=? AND project_id=?').bind(user,projectId).first<any>();
 if(q.get('mode')==='sites')return Response.json({sites:await sites(row.access_token),selected:saved?.site_url||''},{headers:{'Cache-Control':'private, no-store'}});
 if(!saved)throw new HttpError(409,'Choose this website’s Search Console property first.');const days=Number(q.get('days')||28);if(![7,28,90].includes(days))throw new HttpError(400,'Choose 7, 28 or 90 days.');
 const searchType=q.get('searchType')||'web',device=q.get('device')||'',country=q.get('country')||'';if(!['web','image','video','news'].includes(searchType))throw new HttpError(400,'Unsupported Search Console search type.');if(device&&!['DESKTOP','MOBILE','TABLET'].includes(device))throw new HttpError(400,'Unsupported device filter.');
 const dates=searchDates(days),previous={startDate:shift(dates.startDate,-days),endDate:shift(dates.endDate,-days)},endpoint='https://www.googleapis.com/webmasters/v3/sites/'+encodeURIComponent(saved.site_url)+'/searchAnalytics/query';const filters=[country&&{dimension:'country',operator:'equals',expression:country},device&&{dimension:'device',operator:'equals',expression:device}].filter(Boolean);const base={type:searchType,dataState:'final',...(filters.length?{dimensionFilterGroups:[{groupType:'and',filters}]}:{})};
 const plans=[['totals',[],dates],['previousTotals',[],previous],['daily',['date'],dates],['queries',['query'],dates],['pages',['page'],dates]] as const;const results=await Promise.allSettled(plans.map(([name,dimensions,range])=>google(endpoint,row.access_token,{...range,...base,dimensions,rowLimit:['queries','pages'].includes(name)?20:1000})));const reports:Record<string,unknown>={};results.forEach((r,i)=>reports[plans[i][0]]=r.status==='fulfilled'?{status:'available',rows:r.value.rows||[]}:{status:'unavailable',error:r.reason instanceof Error?r.reason.message:'Unable to load this report.'});return Response.json({site:saved.site_url,...dates,previousDates:previous,filters:{country,device,searchType},reports},{headers:{'Cache-Control':'private, no-store'}});
}catch(e){return fail(e)}}
export async function PATCH(request:Request){try{const {row,user,projectId}=await connection(request),b=await body(request),available=await sites(row.access_token);if(!available.some((s:any)=>s.siteUrl===b.siteUrl))throw new HttpError(400,'Choose a Search Console property accessible to your Google account.');await db().prepare('INSERT INTO google_search_sites(user_id,project_id,site_url) VALUES (?,?,?) ON CONFLICT(user_id,project_id) DO UPDATE SET site_url=excluded.site_url').bind(user,projectId,b.siteUrl).run();return Response.json({saved:true})}catch(e){return fail(e)}}
