import {db,fail,body,HttpError} from '@/lib/server';
import {connection,google} from '@/lib/google-analytics-server';
import {searchDates} from '@/lib/analytics-dashboard-data';
async function sites(token:string){const d=await google('https://www.googleapis.com/webmasters/v3/sites',token);return (d.siteEntry||[]).filter((s:any)=>s.permissionLevel!=='siteUnverifiedUser')}
export async function GET(request:Request){try{const {row,user,projectId}=await connection(request),q=new URL(request.url).searchParams;const saved=await db().prepare('SELECT site_url FROM google_search_sites WHERE user_id=? AND project_id=?').bind(user,projectId).first<any>();
 if(q.get('mode')==='sites')return Response.json({sites:await sites(row.access_token),selected:saved?.site_url||''},{headers:{'Cache-Control':'private, no-store'}});
 if(!saved)throw new HttpError(409,'Choose this website’s Search Console property first.');const days=Number(q.get('days')||28);if(![7,28,90].includes(days))throw new HttpError(400,'Choose 7, 28 or 90 days.');const dates=searchDates(days),endpoint='https://www.googleapis.com/webmasters/v3/sites/'+encodeURIComponent(saved.site_url)+'/searchAnalytics/query';
 const plans=[['totals',[]],['daily',['date']],['queries',['query']]] as const;const results=await Promise.allSettled(plans.map(([name,dimensions])=>google(endpoint,row.access_token,{...dates,type:'web',dataState:'final',dimensions,rowLimit:name==='queries'?20:1000})));const reports:Record<string,unknown>={};results.forEach((r,i)=>reports[plans[i][0]]=r.status==='fulfilled'?{status:'available',rows:r.value.rows||[]}:{status:'unavailable',error:r.reason.message});return Response.json({site:saved.site_url,...dates,reports},{headers:{'Cache-Control':'private, no-store'}});
}catch(e){return fail(e)}}
export async function PATCH(request:Request){try{const {row,user,projectId}=await connection(request),b=await body(request),available=await sites(row.access_token);if(!available.some((s:any)=>s.siteUrl===b.siteUrl))throw new HttpError(400,'Choose a Search Console property accessible to your Google account.');await db().prepare('INSERT INTO google_search_sites(user_id,project_id,site_url) VALUES (?,?,?) ON CONFLICT(user_id,project_id) DO UPDATE SET site_url=excluded.site_url').bind(user,projectId,b.siteUrl).run();return Response.json({saved:true})}catch(e){return fail(e)}}
