import {db,fail,HttpError,sameOrigin,ownedProject} from '@/lib/server';
import {currentAccount,randomToken} from '@/lib/accounts';

const cfg=()=>({id:process.env.GOOGLE_CLIENT_ID,secret:process.env.GOOGLE_CLIENT_SECRET,redirect:process.env.GOOGLE_REDIRECT_URI||new URL('/api/analytics/callback',process.env.PUBLIC_APP_URL||'http://localhost:5174').toString()});
async function user(){const u=await currentAccount();if(!u)throw new HttpError(401,'Sign in first.');return u}
export async function GET(request:Request){try{const u=await user();const url=new URL(request.url);if(url.pathname.endsWith('/callback'))return callback(request);const projectId=url.searchParams.get('projectId');const row=projectId?await db().prepare('SELECT property_id,created_at,updated_at FROM google_project_connections WHERE user_id=? AND project_id=?').bind(u.id,projectId).first<any>():await db().prepare('SELECT property_id,created_at,updated_at FROM google_connections WHERE user_id=?').bind(u.id).first<any>();return Response.json({connected:!!row,connection:row||null})}catch(e){return fail(e)}}
export async function POST(request:Request){try{const u=await user();if(!sameOrigin(request))throw new HttpError(403,'Invalid request origin.');const c=cfg();if(!c.id||!c.secret)throw new HttpError(503,'Google Analytics is not configured yet.');const projectId=new URL(request.url).searchParams.get('projectId');if(!projectId)throw new HttpError(400,'Select a website before connecting Google Analytics.');await ownedProject(projectId,u.id);const state=randomToken();await db().prepare('INSERT INTO google_project_oauth_states (state,user_id,project_id,expires_at) VALUES (?,?,?,?)').bind(state,u.id,projectId,Date.now()+600000).run();const qs=new URLSearchParams({client_id:c.id,redirect_uri:c.redirect,response_type:'code',scope:'https://www.googleapis.com/auth/analytics.readonly',access_type:'offline',prompt:'consent',state});return Response.json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+qs})}catch(e){return fail(e)}}
async function callback(request:Request){const q=new URL(request.url).searchParams;const state=q.get('state'),code=q.get('code');if(!state||!code)throw new HttpError(400,'Google authorization was incomplete.');const s=await db().prepare('SELECT * FROM google_project_oauth_states WHERE state=? AND expires_at>?').bind(state,Date.now()).first<any>();if(!s)throw new HttpError(400,'Google authorization expired.');const u=await user();if(s.user_id!==u.id)throw new HttpError(403,'Reconnect from the account that started authorization.');await ownedProject(s.project_id,u.id);const c=cfg();const token=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:c.id!,client_secret:c.secret!,redirect_uri:c.redirect,grant_type:'authorization_code'})}).then(r=>r.json() as Promise<any>);if(!token.refresh_token)throw new HttpError(400,'Google did not return a refresh token. Reconnect and approve access.');const now=new Date().toISOString();const userId=s.user_id,projectId=s.project_id;await db().prepare('INSERT INTO google_project_connections (user_id,project_id,access_token,refresh_token,expires_at,property_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(user_id,project_id) DO UPDATE SET access_token=excluded.access_token,refresh_token=excluded.refresh_token,expires_at=excluded.expires_at,updated_at=excluded.updated_at').bind(userId,projectId,token.access_token,token.refresh_token,Date.now()+Number(token.expires_in||3600)*1000,null,now,now).run();await db().prepare('DELETE FROM google_project_oauth_states WHERE state=?').bind(state).run();return new Response(null,{status:303,headers:{Location:'/account?analytics=connected','Cache-Control':'no-store'}})}

