'use client';
import {useEffect,useState} from 'react';
import './suite.css';
import './account-design.css';
import {ArrowUpRight,ScanSearch,Layers,LockKeyhole} from 'lucide-react';
type User={id:string,email:string,name:string,role:string,status:string};
export default function AccountPanel({initialUser=null}:{initialUser?:User|null}){
 const [user,setUser]=useState(initialUser),[mode,setMode]=useState('login'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState(''),[users,setUsers]=useState<User[]>([]);
 async function request(data:unknown,path='account',method='POST'){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
 async function refreshUsers(){const r=await fetch('/api/users');const d:any=await r.json();if(r.ok)setUsers(d.users);else setError(d.error)}
 useEffect(()=>{if(user?.role==='admin')void refreshUsers()},[user?.role]);
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();setBusy(true);setError('');setNotice('');try{const values=Object.fromEntries(new FormData(e.currentTarget));const d=await request({...values,action});if(d.recoveryCode){setRecovery(d.recoveryCode);setMode(action==='register'?'registered':'login')}else if(action==='login'){window.location.href='/'}else if(action==='password'){window.location.href='/account'}else {setNotice('Profile updated.');setUser(u=>u?{...u,name:String(values.name)}:u)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className={'account-page '+(!user?'auth-designed':'account-settings')}><a href="/" className="suite-brand">g<span>p</span><b className="auth-wordmark">GrowthPilot</b></a>{!user&&<aside className="auth-story"><div className="auth-eyebrow">YOUR NEXT CHAPTER OF GROWTH</div><h2>See the opportunity.<br/><em>Make your next move.</em></h2><p>A clearer view of your website. A focused plan for what comes next.</p><div className="auth-feature"><ScanSearch size={22}/><div><strong>Understand your website</strong><span>Discover what’s working and what needs attention.</span></div></div><div className="auth-feature"><Layers size={22}/><div><strong>Keep your research together</strong><span>Bring audits, keywords, and action plans into one place.</span></div></div><div className="auth-story-footer"><span>Built for your next step.</span><ArrowUpRight size={28}/></div></aside>}<section className="suite-panel account-card">{!user&&<div className="auth-form-eyebrow"><LockKeyhole size={16}/> YOUR PRIVATE WORKSPACE</div>}<h1>{user?'Your account':mode==='register'?'Start growing.':mode==='recover'?'Let’s get you back in.':mode==='registered'?'You’re all set.':'Welcome back.'}</h1><p>{user?user.email:mode==='register'?'Create an account and give your next idea room to grow.':mode==='recover'?'Use your saved recovery code to set a new password.':'Sign in to pick up where you left off.'}</p>{error&&<p className="suite-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {recovery&&<div className="suite-note"><strong>Save your recovery code</strong><p>Keep it somewhere private. You will need it to reset a forgotten password. Each recovery code works once. You can also request a password reset by email.</p><code style={{overflowWrap:'anywhere',userSelect:'all'}}>{recovery}</code><p><a href={mode==='registered'?'/':'/account'}>{mode==='registered'?'Continue to workspace':'Sign in with your new password'}</a></p></div>}
 {!user&&!recovery&&<><form className="account-form" onSubmit={e=>submit(e,mode)}>{mode==='register'&&<label>Full name<input name="name" required maxLength={80} autoComplete="name"/></label>}<label>Email<input name="email" type="email" required autoComplete="email" maxLength={254}/></label>{mode==='recover'&&<label>Recovery code<input name="code" required autoComplete="off"/></label>}<label>{mode==='recover'?'New password':'Password'}<input name="password" type="password" required minLength={mode==='login'?1:12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode!=='login'&&<small>Use at least 12 characters.</small>}<button className="suite-primary" disabled={busy}>{busy?'Please wait…':mode==='register'?'Create account':mode==='recover'?'Reset password':'Sign in'}</button></form><div className="suite-actions">{['login','register','recover'].filter(x=>x!==mode).map(x=><button key={x} onClick={()=>{if(x==='recover'){window.location.href='/reset-password';return}setMode(x);setError('')}}>{x==='login'?'Sign in':x==='register'?'Create account':'Forgot password?'}</button>)}</div></>}
 {user&&<><form className="account-form" onSubmit={e=>submit(e,'profile')}><label>Display name<input name="name" defaultValue={user.name} required maxLength={80}/></label><button className="suite-primary" disabled={busy}>Save profile</button></form><h2>Security &amp; password</h2><p><a href="/reset-password">Forgot your current password? Reset by email</a></p><p>Choose a strong password to protect your workspace.</p><form className="account-form" onSubmit={e=>submit(e,'password')}><label>Current password<input type="password" name="current" required maxLength={128} autoComplete="current-password"/></label><label>New password<input type="password" name="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><small>Use 12–128 characters. Updating your password signs you out on all devices.</small><button className="suite-primary" disabled={busy}>Update password</button></form><button disabled={busy} onClick={async()=>{setBusy(true);try{await request({action:'logout'});window.location.href='/account'}catch(e){setError((e as Error).message);setBusy(false)}}}>Sign out of all devices</button><p><a href="/">Back to workspace</a></p></>}
 </section>{user?.role==='admin'&&<section className="suite-panel"><h2>User management</h2><p>Role changes and account suspension revoke that user’s sessions.</p><div className="suite-table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td>{(['role','status'] as const).map(key=><td key={key}><select aria-label={`${key} for ${u.email}`} value={u[key]} disabled={busy||u.id===user.id} onChange={async e=>{setBusy(true);setError('');try{await request({...u,[key]:e.target.value},'users','PATCH');await refreshUsers()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{(key==='role'?['member','admin']:['active','disabled']).map(v=><option key={v}>{v}</option>)}</select></td>)}</tr>)}</tbody></table></div></section>}</main>
}


