'use client';
import {useEffect,useRef,useState} from 'react';
import './seo-toolkit.css';
export default function AiWriter({projectId,records,onSave,onOpenContent,onOpenSaved,social=false}:{projectId:string,records:any[],onSave:(data:Record<string,string>)=>Promise<void>,onOpenContent:()=>void,onOpenSaved?:()=>void,social?:boolean}){
 const [selected,setSelected]=useState(''),[draft,setDraft]=useState(''),[title,setTitle]=useState(''),[channel,setChannel]=useState('linkedin'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);const sources=records.filter(r=>r.kind==='content'),source=sources.find(r=>r.id===selected);
 async function generate(){if(!source)return;if(draft&&!confirm('Replace the current unsaved draft?'))return;setBusy(true);setError('');try{const r=await fetch('/api/content-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,recordId:source.id,format:social?channel:'article'})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to generate a draft.');if(mounted.current){setDraft(d.draft);setTitle((social?'Post: ':'Draft: '+source.data.title).slice(0,500));setSaved(false)}}catch(e){if(mounted.current)setError((e as Error).message)}finally{if(mounted.current)setBusy(false)}}
 async function save(){if(!source)return;setBusy(true);setError('');try{await onSave(social?{title:title.trim(),channel,date,status:'Draft',body:draft.trim(),url:''}:{title:title.trim(),body:draft.trim(),keyword:source.data.keyword||'',notes:('AI-assisted draft. Source brief: '+source.data.title+' (record '+source.id+'). Review all claims before publishing.').slice(0,8000)});if(mounted.current)setSaved(true)}catch(e){if(mounted.current)setError((e as Error).message)}finally{if(mounted.current)setBusy(false)}}
 const openSaved=onOpenSaved||onOpenContent;
 return <section className="suite-panel toolkit"><header><h2>{social?'AI Post Writer':'AI Writer'}</h2><p>{social?'Turn a saved brief into an editable LinkedIn or X post for your publishing calendar.':'Turn a saved brief into an editable article or implementation guide for this website.'}</p></header><div className="toolkit-body">{!sources.length?<><p>Save a brief from the Opportunity Feed, or add content in My Content, to get started.</p><button onClick={onOpenContent}>Open My Content →</button></>:<><label>Saved brief / source content<select disabled={busy} value={selected} onChange={e=>{if(draft&&!saved&&!confirm('Discard the unsaved draft and change source?'))return;setSelected(e.target.value);setDraft('');setTitle('');setError('');setSaved(false)}}><option value="">Select a source</option>{sources.map(r=><option key={r.id} value={r.id}>{r.data.title}</option>)}</select></label>{social&&<label>Channel<select disabled={busy} value={channel} onChange={e=>{setChannel(e.target.value);setDraft('');setSaved(false)}}><option value="linkedin">LinkedIn</option><option value="x">X</option></select></label>}{source&&<details><summary>Review source brief</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:250,overflow:'auto'}}>{source.data.body}</pre></details>}<p>Generation sends the selected source and latest brand profile to OpenAI. Review factual claims and any [VERIFY] placeholders. Saving creates a new draft and preserves the source.</p><button disabled={!source||busy} onClick={()=>void generate()}>{busy?'Working…':social?'Generate post draft':'Generate article draft'}</button>{draft&&<><label>{social?'Post title':'Draft title'}<input maxLength={500} disabled={busy||saved} value={title} onChange={e=>setTitle(e.target.value)}/></label>{social&&<label>Planned date<input type="date" disabled={busy||saved} value={date} onChange={e=>setDate(e.target.value)}/></label>}<label>{social?channel==='x'?'Post (max 250 characters)':'Post':'Article (Markdown)'}<textarea rows={social?10:22} maxLength={social?(channel==='x'?250:2000):8000} disabled={busy||saved} value={draft} onChange={e=>setDraft(e.target.value)}/></label><p>{draft.length} characters · Draft only; no automatic publication.</p>{saved?<><p role="status">Saved to {social?'Social Calendar':'My Content'}.</p><button onClick={openSaved}>Open {social?'Social Calendar':'My Content'} →</button></>:<button disabled={busy||!title.trim()||!draft.trim()||(!date&&social)} onClick={()=>void save()}>Save to {social?'Social Calendar':'My Content'}</button>}</>}</>}</div></section>
}
