'use client';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import {delta,trendRows} from '@/lib/analytics-dashboard-data';
import './analytics-dashboard.css';
import AuditReport from './audit-report';
import {PageShell} from './dashboard/page-shell';
type Project={id:string,name:string,url:string};
async function request(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load this report.');return d}
const format=(v:any,kind='number')=>typeof v!=='number'?'—':kind==='percent'?(v*100).toFixed(1)+'%':kind==='seconds'?Math.round(v)+'s':v.toLocaleString(undefined,{maximumFractionDigits:2});
function ReportTable({report,columns}:{report:any,columns:[string,string,string?][]}){if(!report)return <p className="ga-empty">Not loaded.</p>;if(report.status==='unavailable')return <p className="ga-error">{report.error}</p>;if(!report.rows?.length)return <p className="ga-empty">No data returned for this period.</p>;return <><div className="ga-table"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{report.rows.map((r:any,i:number)=><tr key={i}>{columns.map(([key,,kind])=><td key={key}>{typeof r[key]==='number'?format(r[key],kind):String(r[key]??'—')}</td>)}</tr>)}</tbody></table></div>{report.metadata?.subjectToThresholding&&<p className="ga-note">Google applied privacy thresholds to this report.</p>}{report.metadata?.samplingMetadatas?.length>0&&<p className="ga-note">Google returned sampled data.</p>}{report.metadata?.dataLossFromOtherRow&&<p className="ga-note">Some values are grouped into Google’s “other” row.</p>}</>}
function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="ga-card"><h2>{title}</h2>{children}</section>}
function Chart({rows,search=false}:{rows:any[],search?:boolean}){if(!rows.length)return <p className="ga-empty">No trend data returned.</p>;return <div className="ga-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid stroke="#edf0f6" vertical={false}/><XAxis dataKey={search?'date':'day'} tick={{fontSize:11}} minTickGap={25}/><YAxis tick={{fontSize:11}} width={50}/><Tooltip/><Legend/><Line type="monotone" dataKey={search?'clicks':'current'} name={search?'Search clicks':'Current period'} stroke="#6a4de5" dot={false} strokeWidth={2}/>{!search&&<Line type="monotone" dataKey="previous" name="Previous period" stroke="#a9b9d4" dot={false} strokeDasharray="5 5"/>}</LineChart></ResponsiveContainer></div>}
export default function AnalyticsDashboard(){const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;request('/api/projects').then(d=>{if(!active)return;setProjects(d.projects);const wanted=new URLSearchParams(window.location.search).get('projectId');setSelected(d.projects.some((p:Project)=>p.id===wanted)?wanted!:d.projects[0]?.id||'')}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const project=projects.find(p=>p.id===selected);return <PageShell active="analytics" projectId={selected}><main className="ga-page"><header className="ga-page-header"><div><a href="/">← GrowthPilot workspace</a><h1>Google Analytics</h1><p>Your website’s audience, acquisition and content performance.</p></div><label>Website<select aria-label="Analytics website" value={selected} onChange={e=>{setSelected(e.target.value);window.history.replaceState(null,'','/analytics?projectId='+encodeURIComponent(e.target.value))}}><option value="" disabled>Select website</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></header>{error&&<p className="ga-error">{error}</p>}{loading?<p className="ga-empty">Loading websites…</p>:project?<WebsiteAnalytics key={project.id} project={project}/>:<Card title="Add a website first"><a href="/">Return to your workspace to add a website.</a></Card>}</main></PageShell>
}
function WebsiteAnalytics({project}:{project:Project}){
 const [properties,setProperties]=useState<any[]>([]),[property,setProperty]=useState(''),[saved,setSaved]=useState(''),[days,setDays]=useState(28),[revision,setRevision]=useState(0),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[setup,setSetup]=useState(true),[saving,setSaving]=useState(false),[trend,setTrend]=useState('sessions');
 const [speed,setSpeed]=useState<any>(null);
 useEffect(()=>{let active=true;request('/api/projects/'+encodeURIComponent(project.id)).then(d=>{if(active)setSpeed(d.audits.find((a:any)=>a.performance)||null)}).catch(()=>{});return()=>{active=false}},[project.id]); const endpoint='/api/analytics/reports?projectId='+encodeURIComponent(project.id);
 useEffect(()=>{let active=true;request(endpoint+'&mode=properties').then(d=>{if(active){setProperties(d.properties);setProperty(d.selected||'');setSaved(d.selected||'')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setSetup(false)});return()=>{active=false}},[endpoint]);
 useEffect(()=>{if(!saved)return;let active=true;const controller=new AbortController();setReport(null);setLoading(true);setError('');request(endpoint+'&mode=dashboard&days='+days,{signal:controller.signal}).then(d=>{if(active)setReport(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;controller.abort()}},[endpoint,saved,days,revision]);
 async function connect(search=false){setSaving(true);setError('');try{const d=await request('/api/analytics?projectId='+encodeURIComponent(project.id)+(search?'&search=1':''),{method:'POST'});window.location.assign(d.url)}catch(e){setError((e as Error).message);setSaving(false)}}
 async function save(){setSaving(true);setReport(null);setError('');try{await request(endpoint,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId:property})});if(property===saved)setRevision(v=>v+1);else setSaved(property)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 const reports=report?.reports||{},overview=reports.overview,current=overview?.rows?.find((r:any)=>r.dateRange==='current')||{},previous=overview?.rows?.find((r:any)=>r.dateRange==='previous')||{};
 return <><section className="ga-controls"><div><strong>{project.name}</strong><p>{project.url}</p></div><label>GA4 property<select value={property} disabled={setup||saving||loading} onChange={e=>setProperty(e.target.value)}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.account} / {p.name} ({p.id})</option>)}</select></label><button disabled={!property||saving||loading} onClick={save}>Save property</button><label>Period<select value={days} disabled={saving} onChange={e=>setDays(Number(e.target.value))}>{[7,28,90].map(n=><option key={n} value={n}>Last {n} days</option>)}</select></label><button disabled={!saved||loading||saving} onClick={()=>setRevision(v=>v+1)}>Refresh</button><button disabled={saving} onClick={()=>void connect()}>Connect / reconnect Google</button></section><p className="ga-note">Saved separately for this website. Reports cover the entire selected GA4 property, through yesterday in its reporting time zone; select a property dedicated to this website. Users can appear in multiple groups.</p>{error&&<p role="alert" className="ga-error">{error}</p>}{setup||loading?<p className="ga-empty" role="status">Loading Google reports…</p>:!saved?<Card title="Choose your website’s GA4 property"><p>Connect Google, choose the matching property above and save it once. Selecting this website will then load its reports automatically.</p></Card>:report&&<>
 <div className="ga-metrics">{[['activeUsers','Active users'],['sessions','Sessions'],['screenPageViews','Page / screen views'],['keyEvents','Key events']].map(([key,label])=>{const change=delta(current[key],previous[key]);return <section key={key}><span>{label}</span><strong>{format(current[key])}</strong><small>{change===null?'No comparable previous value':`${change>=0?'+':''}${change.toFixed(1)}% vs previous ${days} days`}</small></section>})}</div>{overview?.status==='unavailable'&&<p className="ga-error">{overview.error}</p>}{overview?.status==='available'&&!overview.rows.length&&<p className="ga-note">Google returned no overview data for these periods.</p>}
 <Card title="Audience growth"><label>Trend metric <select value={trend} onChange={e=>setTrend(e.target.value)}><option value="sessions">Sessions</option><option value="activeUsers">Active users</option><option value="screenPageViews">Views</option></select></label>{reports.daily?.status==='available'?<Chart rows={reports.daily.rows.length?trendRows(reports.daily.rows,days,trend,new Date(report.fetchedAt),reports.daily.metadata?.timeZone):[]}/>:<p className="ga-error">{reports.daily?.error}</p>}<p className="ga-note">Day 1–{days} of each period. Daily active users are not added together to calculate unique users.</p></Card>
 <div className="ga-grid"><Card title="Acquisition channels"><ReportTable report={reports.channels} columns={[["sessionDefaultChannelGroup","Channel"],["sessions","Sessions"],["engagedSessions","Engaged sessions"],["engagementRate","Engagement rate","percent"]]}/></Card><Card title="Top cities"><ReportTable report={reports.cities} columns={[["city","City"],["country","Country"],["activeUsers","Active users"],["sessions","Sessions"]]}/></Card></div>
 <Card title="New and returning visitors"><ReportTable report={reports.visitors} columns={[["newVsReturning","Visitor type"],["activeUsers","Active users"],["sessions","Sessions"],["screenPageViews","Views"],["screenPageViewsPerSession","Views / session"],["averageSessionDuration","Avg. session duration","seconds"]]}/><p className="ga-note">Visitor groups can overlap over the reporting period and may include unclassified users.</p></Card>
 <Card title="Top content"><ReportTable report={reports.pages} columns={[["pageTitle","Page title"],["pagePath","Path"],["screenPageViews","Views"],["sessions","Sessions"],["engagementRate","Engagement rate","percent"],["averageSessionDuration","Avg. session duration","seconds"]]}/><p className="ga-note">Top 20 title/path combinations by views. Session counts across pages are not additive.</p></Card>
 <div className="ga-grid"><Card title="Devices"><ReportTable report={reports.devices} columns={[["deviceCategory","Device"],["activeUsers","Active users"],["sessions","Sessions"]]}/></Card><Card title="Organic search visitors · GA4"><ReportTable report={reports.organic} columns={[["activeUsers","Active users"],["sessions","Sessions"],["keyEvents","Key events"]]}/><p className="ga-note">All organic search engines, as classified by GA4. This is not Search Console clicks.</p></Card></div>
 <Card title="Revenue recorded in GA4"><ReportTable report={reports.revenue} columns={[["totalRevenue","Total revenue"],["totalAdRevenue","Ad revenue"],["publisherAdImpressions","Ad impressions"],["publisherAdClicks","Ad clicks"]]}/><p className="ga-note">Currency: {reports.revenue?.metadata?.currencyCode||'not returned'}. Requires revenue/ad tracking in GA4. These are GA4 measurements, not an AdSense earnings or payout report.</p></Card><p className="ga-note">Source: Google Analytics Data API · {report.property} · Retrieved {new Date(report.fetchedAt).toLocaleString()} · Top lists are limited; they may not sum to overall totals.</p>
 </>}
 <SearchReports projectId={project.id} days={days} connect={()=>void connect(true)}/><Card title="Page experience">{speed?<><p className="ga-note">Latest saved PageSpeed audit: {new Date(speed.created_at).toLocaleString()}. Independent of the Analytics reporting period.</p><AuditReport performance={speed.performance} url={project.url}/></>:<p>Run a website audit under SEO → Site Audit to collect mobile and desktop PageSpeed measurements.</p>}</Card></>
}
function SearchReports({projectId,days,connect}:{projectId:string,days:number,connect:()=>void}){
 const [sites,setSites]=useState<any[]>([]),[site,setSite]=useState(''),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const endpoint='/api/analytics/search?projectId='+encodeURIComponent(projectId);
 useEffect(()=>{let active=true;setReport(null);setError('');setBusy(true);request(endpoint+'&days='+days).then(d=>{if(active){setReport(d);setSite(d.site)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[endpoint,days,refresh]);
 async function loadSites(){setBusy(true);setError('');try{const d=await request(endpoint+'&mode=sites');setSites(d.sites);setSite(d.selected||'');if(!d.sites.length)setError('No accessible Search Console properties were returned for this account.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){setBusy(true);try{await request(endpoint,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({siteUrl:site})});setRefresh(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const totals=report?.reports?.totals?.rows?.[0];return <Card title="Google Search performance · Search Console"><div className="ga-search-controls"><button onClick={connect}>Authorize Search Console</button><button disabled={busy} onClick={loadSites}>Choose Search Console property</button>{sites.length>0&&<><select aria-label="Search Console property" value={site} onChange={e=>setSite(e.target.value)}><option value="">Select property</option>{sites.map(s=><option key={s.siteUrl}>{s.siteUrl}</option>)}</select><button disabled={busy||!site} onClick={save}>Save search property</button></>}</div>{error&&<p className="ga-note">{error} Search Console requires its API enabled and additional read permission.</p>}{busy&&<p role="status">Loading search data…</p>}{report&&<><p className="ga-note">{report.site} · {report.startDate} to {report.endDate} · Pacific time · Finalized web-search data only; recent dates may be delayed. This covers the selected Search Console property.</p>{report.reports.totals.status==='unavailable'?<p className="ga-error">{report.reports.totals.error}</p>:totals?<div className="ga-metrics">{[['impressions','Search impressions'],['clicks','Search clicks'],['ctr','Click-through rate'],['position','Average position']].map(([key,label])=><section key={key}><span>{label}</span><strong>{format(totals[key],key==='ctr'?'percent':'number')}</strong></section>)}</div>:<p className="ga-empty">No finalized search totals returned.</p>}{report.reports.daily.status==='available'?<Chart search rows={report.reports.daily.rows.map((r:any)=>({date:r.keys[0],clicks:r.clicks})).sort((a:any,b:any)=>a.date.localeCompare(b.date))}/>:<p className="ga-error">{report.reports.daily.error}</p>}<h3>Top search queries</h3><ReportTable report={{...report.reports.queries,rows:report.reports.queries.rows?.map((r:any)=>({...r,query:r.keys[0]}))}} columns={[["query","Query"],["clicks","Clicks"],["impressions","Impressions"],["ctr","CTR","percent"],["position","Average position"]]}/><p className="ga-note">Top 20 queries. Anonymized queries are omitted by Google; query rows need not sum to overall totals.</p></>}</Card>
}

