'use client';
import {useEffect,useState} from 'react';
export default function AnalyticsPanel({projectId}:{projectId:string}){
 const [properties,setProperties]=useState<{id:string,name:string,account:string}[]>([]),[selected,setSelected]=useState(''),[days,setDays]=useState('28'),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const endpoint='/api/analytics/reports?projectId='+encodeURIComponent(projectId);
 async function request(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 useEffect(()=>{let active=true;setBusy(true);request(endpoint+'&mode=properties').then(d=>{if(active){setProperties(d.properties);setSelected(d.selected||'')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[endpoint]);
 async function load(){setBusy(true);setError('');setReport(null);try{await request(endpoint,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId:selected})});setReport(await request(endpoint+'&days='+days))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="suite-panel" style={{padding:24,marginBottom:20}}><h2>Google Analytics · website connection</h2><p><a href={"/analytics?projectId="+encodeURIComponent(projectId)}>Open full Google Analytics dashboard →</a></p><p>Select the GA4 property belonging to this website. Reports cover the full property, through yesterday.</p>{error&&<p role="alert" className="suite-error">{error}</p>}<div className="suite-actions"><select aria-label="GA4 property" value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);setReport(null)}}><option value="">Choose a property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.account} / {p.name} ({p.id})</option>)}</select><select aria-label="Reporting period" value={days} disabled={busy} onChange={e=>{setDays(e.target.value);setReport(null)}}>{[7,28,90].map(n=><option key={n} value={n}>Last {n} days</option>)}</select><button disabled={busy||!selected} onClick={load}>{busy?'Loading…':'Save property & load report'}</button></div>{!busy&&!error&&!properties.length&&<p>No accessible GA4 properties. Connect a Google account with access to your website’s Analytics.</p>}{report&&<><p>Property: {report.property} · Retrieved {new Date(report.fetchedAt).toLocaleString()}</p>{report.empty?<p>No data returned for this period.</p>:<div className="suite-metrics">{['Active users','Sessions','Page / screen views','Key events'].map((name,i)=><div className="suite-metric" key={name}><span>{name}</span><strong>{report.metrics[i]?.toLocaleString()??'—'}</strong></div>)}</div>}</>}</section>;
}

