'use client';
import {useState} from 'react';
import './audit-report.css';
const tone=(score:number|null)=>score===null?'muted':score>=90?'good':score>=50?'warn':'bad';
const clean=(text:string='')=>text.replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/`/g,'');
function Ring({score,label}:{score:number|null,label:string}){return <div className="audit-score"><div className={'audit-ring '+tone(score)}>{score??'—'}</div><strong>{label}</strong><small>{score===null?'Not measured':'out of 100'}</small></div>}
export default function AuditReport({performance,url}:{performance:any,url:string}){
 const [device,setDevice]=useState<'mobile'|'desktop'>('mobile');const report=performance?.[device];
 const metric=(label:string,value:any,unit:string)=> <div key={label}><span>{label}</span><strong>{typeof value==='number'?(unit==='s'?(value/1000).toFixed(2):unit===''?value.toFixed(3):Math.round(value))+' '+unit:'Unavailable'}</strong></div>;
 const field=report?.field?.metrics;
 return <section className="audit-report"><header><div><small>GOOGLE PAGESPEED INSIGHTS</small><h2>Page experience & technical report</h2><p>Tests the website’s entry URL. These scores are separate from the multi-page HTML crawl.</p></div><a href={'https://pagespeed.web.dev/analysis?url='+encodeURIComponent(url)} target="_blank" rel="noreferrer">Open in PageSpeed ↗</a></header>
 <div className="audit-tabs" role="group" aria-label="Test device">{(['mobile','desktop'] as const).map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='mobile'?'Mobile':'Desktop'}</button>)}<button onClick={()=>window.print()}>Print / Save PDF</button></div>
 {report?.status!=='available'?<div className="audit-notice"><h3>Measurement unavailable</h3><p>{report?.reason||'Run a new audit to request measurements from Google.'}</p><p>Your HTML crawl remains available below.</p></div>:<>
 <div className="audit-meta"><span>{report.url||url}</span><span>Measured {new Date(report.measuredAt).toLocaleString()}{report.version?' · Lighthouse '+report.version:''}</span></div>
 <div className="audit-scores">{report.categories?.length?report.categories.map((c:any)=><Ring key={c.id} score={c.score} label={c.title}/>):<Ring score={report.score??null} label="Performance"/>}</div>
 {!report.categories&&<p className="audit-notice">This saved audit contains summary metrics only. Run a new audit for detailed category findings.</p>}
 <section className="audit-block"><h3>Real-user Core Web Vitals</h3><p>URL-level field data supplied by Google. Missing data is not a pass.</p>{field?<div className="audit-values">{metric('LCP',field.LARGEST_CONTENTFUL_PAINT_MS?.percentile,'s')}{metric('INP',field.INTERACTION_TO_NEXT_PAINT?.percentile,'ms')}{metric('CLS',typeof field.CUMULATIVE_LAYOUT_SHIFT_SCORE?.percentile==='number'?field.CUMULATIVE_LAYOUT_SHIFT_SCORE.percentile/100:undefined,'')}</div>:<p className="audit-notice">No real-user field measurements were returned for this URL. Lab results below do not replace field data.</p>}</section>
 <section className="audit-block"><h3>Lab performance metrics</h3><p>A simulated {device} visit, rather than measurements of all visitors.</p><div className="audit-values">{metric('First Contentful Paint',report.fcp,'s')}{metric('Largest Contentful Paint',report.lcp,'s')}{metric('Total Blocking Time',report.tbt,'ms')}{metric('Cumulative Layout Shift',report.cls,'')}{metric('Speed Index',report.speedIndex,'s')}{metric('Server response time',report.ttfb,'ms')}</div></section>
 {report.warnings?.map((w:string,i:number)=><p className="audit-notice" key={i}>{w}</p>)}
 {report.categories?.map((c:any)=>{const pending=c.audits.filter((a:any)=>a.score!==1&&a.mode!=='notApplicable');const passed=c.audits.filter((a:any)=>a.score===1);const na=c.audits.filter((a:any)=>a.mode==='notApplicable');return <section className="audit-block" key={c.id}><div className="audit-category"><h3>{c.title}</h3><span className={tone(c.score)}>{c.score??'—'} / 100</span></div><p>{pending.length} findings or manual checks · {passed.length} passed · {na.length} not applicable</p>{pending.map((a:any)=><details className="audit-finding" key={a.id}><summary><span>{clean(a.title)}</span><small>{a.mode==='manual'?'Manual check':a.score===null?'Not scored':a.score===0?'Needs attention':'Review'}{a.displayValue?' · '+a.displayValue:''}</small></summary><p>{clean(a.description)}</p>{a.savingsMs>0&&<p>Estimated time saving: {Math.round(a.savingsMs)} ms. Savings overlap and should not be added together.</p>}{a.savingsBytes>0&&<p>Estimated transfer saving: {Math.round(a.savingsBytes/1024)} KiB.</p>}</details>)}{passed.length>0&&<details className="audit-finding"><summary>Passed checks ({passed.length})</summary><ul>{passed.map((a:any)=><li key={a.id}>{clean(a.title)}</li>)}</ul></details>}</section>})}
 <p className="audit-meta">{report.note}</p></>}
 </section>
}
