'use client';
import {useState} from 'react';
import './audit-summary.css';
function Ring({score,label,large=false}:{score:number|null,label:string,large?:boolean}){const value=typeof score==='number'&&Number.isFinite(score)?Math.max(0,Math.min(100,score)):null;const color=value===null?'#9aa4b5':value>=90?'#20b879':value>=50?'#edae27':'#ef5276';return <div className={'gp-overview-gauge '+(large?'large':'')}><svg viewBox="0 0 120 120" role="img" aria-label={label+': '+(value===null?'not measured':value+' out of 100')}><circle cx="60" cy="60" r="51" fill="none" stroke="#edf1f8" strokeWidth="9"/><circle cx="60" cy="60" r="51" fill="none" stroke={color} strokeWidth="9" strokeLinecap="round" strokeDasharray={`${(value??0)*3.2044} 320.44`} transform="rotate(-90 60 60)"/><text x="60" y="65" textAnchor="middle" fill="#344661" fontSize="25" fontWeight="650">{value??'—'}</text></svg><strong>{label}</strong><small>{value===null?'Not measured':'Score out of 100'}</small></div>}
export default function AuditSummary({project,audit,busy,onRun,onView,openActions}:{project:{name:string,url:string},audit:any,busy:boolean,onRun:()=>void,onView:()=>void,openActions:number}){
 const [device,setDevice]=useState<'mobile'|'desktop'>('mobile');const report=audit?.performance?.[device];const available=report?.status==='available';const score=(id:string)=>available?(report.categories?.find((c:any)=>c.id===id)?.score??(id==='performance'?report.score:null)??null):null;const main=score('performance');const screenshot=(d:string)=>{const s=audit?.performance?.[d]?.screenshot;return typeof s==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s)?s:null};
 return <section className="suite-panel gp-audit-overview"><div className="suite-panelhead"><div><h2>Audit results</h2><p>{project.name} · <a href={project.url} target="_blank" rel="noreferrer">{new URL(project.url).hostname} ↗</a></p></div><div className="gp-overview-buttons"><button disabled={!audit} onClick={onView}>View full report →</button><button className="suite-primary" disabled={busy} onClick={onRun}>{busy?'Auditing…':'Run audit'}</button></div></div><div className="gp-overview-device" role="group" aria-label="Score device">{(['mobile','desktop'] as const).map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='mobile'?'Mobile':'Desktop'}</button>)}</div><div className="gp-overview-hero"><div className="gp-overview-verdict"><Ring score={main} label={device==='mobile'?'Mobile performance':'Desktop performance'} large/><h3>{main===null?'Run an audit for measurements':main>=90?'Strong lab performance':main>=50?'Performance could be improved':'Performance needs attention'}</h3>{main===null&&audit&&<p>{report?.reason||'No saved performance measurement is available.'}</p>}<button className="gp-overview-findings" onClick={onView} disabled={!audit}>{audit?`${audit.issues.length} HTML issue categories · Review findings`:'No audit yet'}</button></div><div className="gp-overview-previews"><div className="gp-overview-desktop"><div className="gp-overview-browser"><i/><i/><i/><span>Desktop preview</span></div>{screenshot('desktop')?<img src={screenshot('desktop')!} alt={'Desktop rendering of '+project.name}/>:<div className="gp-overview-preview-empty"><strong>Desktop preview</strong><p>A screenshot will appear when a new Google test returns one.</p></div>}</div><div className="gp-overview-phone"><span>Mobile preview</span>{screenshot('mobile')?<img src={screenshot('mobile')!} alt={'Mobile rendering of '+project.name}/>:<div className="gp-overview-preview-empty"><p>No saved screenshot</p></div>}</div></div></div><div className="gp-overview-categories">{[['seo','SEO'],['accessibility','Accessibility'],['best-practices','Best practices'],['performance','Performance']].map(([id,label])=><Ring key={id} score={score(id)} label={label}/>)}<div className="gp-overview-scope"><strong>Audit coverage</strong><span>{audit?.pages.length??0} pages checked</span><span>{openActions} open actions</span><small>Google scores test the entry URL. HTML findings cover the limited crawl.</small></div></div><div className="suite-footer">{audit?`Last audit: ${new Date(audit.created_at).toLocaleString()} · ${audit.coverage||'Limited HTML crawl'}`:'Run your first audit to collect real measurements.'} · Google Lighthouse scores are not an overall website grade.</div></section>
}

