'use client';
import {useEffect,useRef,useState} from 'react';
type Job={status:string,pages:number,queued:number,discovered:number,limit:number,blocked:number,skipped:number,message:string,current:string};
export default function FullCrawl({projectId,visible,onComplete}:{projectId:string,visible:boolean,onComplete:()=>void}){
 const [job,setJob]=useState<Job|null>(null),[limit,setLimit]=useState(500),[error,setError]=useState(''),[working,setWorking]=useState(false);const current=useRef<Job|null>(null),callback=useRef(onComplete);callback.current=onComplete;
 useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;current.current=null;setJob(null);setError('');
  async function poll(){try{const action=current.current?.status==='running'?'step':null;const r=await fetch('/api/crawl'+(action?'':'?projectId='+encodeURIComponent(projectId)),action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,action})}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load crawl progress.');if(stopped)return;const wasRunning=current.current?.status==='running';current.current=d.job;setJob(d.job);setError('');if(wasRunning&&d.job?.status==='complete')callback.current();}catch(e){if(!stopped)setError((e as Error).message)}finally{if(!stopped)timer=setTimeout(poll,current.current?.status==='running'?1000:4000)}}
  void poll();return()=>{stopped=true;clearTimeout(timer)};
 },[projectId]);
 async function act(action:string){setWorking(true);setError('');try{const r=await fetch('/api/crawl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,action,limit})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not update crawl.');current.current=d.job;setJob(d.job)}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 if(!visible&&job?.status!=='running')return null;
 return <section className="suite-panel"><div className="suite-panelhead"><div><h2>Full-site crawler</h2><p style={{fontSize:13,marginTop:8}}>Internal links + XML sitemaps · robots.txt respected · server HTML</p></div><div className="suite-actions">{job?.status==='running'?<button disabled={working} onClick={()=>void act('pause')}>Pause crawl</button>:<>{job?.status==='paused'&&<button disabled={working} onClick={()=>void act('resume')}>Resume saved crawl</button>}<label>Page limit <select aria-label="Full crawl page limit" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[100,500,1000,2000].map(n=><option key={n} value={n}>{n.toLocaleString()}</option>)}</select></label><button className="suite-primary" disabled={working} onClick={()=>{if(job?.status==='paused'&&!confirm('Replace the paused crawl with a new one? Completed audit reports are kept.'))return;void act('start')}}>Start full crawl</button></>}</div></div>{job&&<div style={{padding:'18px 24px'}}><strong>{job.status==='complete'?'Crawl finished — report saved':job.status==='paused'?'Crawl paused':'Crawling…'}</strong><p style={{fontSize:13,margin:'10px 0'}}>{job.pages} pages checked · {job.queued} URLs queued · {job.blocked} blocked by robots · limit {job.limit}</p><progress aria-label="Pages checked against crawl limit" value={job.pages} max={job.limit} style={{width:'100%'}}/><p style={{fontSize:12,overflowWrap:'anywhere',marginTop:8}}>{job.status==='running'?job.current:job.message}</p></div>}{error&&<p className="suite-error" role="alert">{error}</p>}<div className="suite-footer">Keep GrowthPilot open to process batches; navigation within this website’s workspace is fine. Closing the tab or switching websites stops processing after the current batch. Reopen this website to continue from saved progress. Same-origin URLs only; query-string links and JavaScript-rendered links are excluded. Limits may leave a partial crawl. PageSpeed is run separately with Run audit.</div></section>
}

