'use client';
import {useMemo,useState} from 'react';
import {Search,Download,Plus,Check,ArrowRight,BookOpen} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {normalize,numeric,keywordRows,suggestIdeas,coverage,researchBrief,type ResearchRecord,type ResearchPage} from '@/lib/keyword-research';
type Props={project:{id:string,country:string,language:string}|null,records:ResearchRecord[],pages:ResearchPage[],initialKeyword?:string,onSave:(data:Record<string,string>,kind:string)=>Promise<void>,onNavigate:(section:string,tool:string)=>void};
function exportText(name:string,text:string,mime='text/plain'){const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const cell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';
export default function KeywordStudio({project,records,pages,initialKeyword='',onSave,onNavigate}:Props){
 const [input,setInput]=useState(initialKeyword),[keyword,setKeyword]=useState(initialKeyword),[country,setCountry]=useState(project?.country||'United States'),[language,setLanguage]=useState(project?.language||'English');
 const [category,setCategory]=useState('Saved data'),[intent,setIntent]=useState('All'),[maxDifficulty,setMaxDifficulty]=useState(''),[minVolume,setMinVolume]=useState(''),[sort,setSort]=useState('Keyword');
 const [selected,setSelected]=useState<string[]>([]),[list,setList]=useState('Priority keywords'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[brief,setBrief]=useState('');
 const metrics=useMemo(()=>keywordRows(records,country,language),[records,country,language]);
 const matches=metrics.filter(r=>normalize(r.data.title)===normalize(keyword));
 const sources=[...new Set(matches.map(r=>r.data.source||'Unknown source'))];
 const [preferredSource,setPreferredSource]=useState('');const exact=matches.find(r=>r.data.source===preferredSource)||(matches.length===1?matches[0]:undefined);
 const foundPages=coverage(keyword,pages);
 const ideas=category==='Saved data'?metrics.filter(r=>!keyword||normalize(r.data.title).includes(normalize(keyword))).map(r=>({term:r.data.title,intent:r.data.intent||'',volume:numeric(r.data.volume),difficulty:numeric(r.data.difficulty),cpc:numeric(r.data.cpc),source:r.data.source||'Unspecified source',date:r.data.date||'',currency:r.data.currency||''})):suggestIdeas(keyword,category).map(term=>({term,intent:'',volume:null,difficulty:null,cpc:null,source:'Planning template — unmeasured',date:'',currency:''}));
 const filtered=ideas.filter(r=>(intent==='All'||normalize(r.intent)===normalize(intent))&&(!minVolume||(r.volume!==null&&r.volume>=Number(minVolume)))&&(!maxDifficulty||(r.difficulty!==null&&r.difficulty<=Number(maxDifficulty)))).sort((a,b)=>sort==='Volume'?(b.volume??-1)-(a.volume??-1):sort==='Difficulty'?(a.difficulty??101)-(b.difficulty??101):a.term.localeCompare(b.term));
 const shortlist=records.filter(r=>r.kind==='keyword-list'&&normalize(r.data.country||'')===normalize(country)&&normalize(r.data.language||'')===normalize(language));
 function resetSelection(){setSelected([]);setMessage('')}
 async function saveSelected(){if(!project)return;setBusy(true);setMessage('');let count=0;try{for(const term of selected){if(shortlist.some(r=>normalize(r.data.title)===normalize(term)&&normalize(r.data.list)===normalize(list)))continue;await onSave({title:term,list,country,language,notes:'Saved from Keyword Overview. Measurements remain attached to their original source records.'},'keyword-list');count++}setMessage(`${count} keywords saved to ${list}. Existing entries skipped.`);setSelected([])}catch(e){setMessage(`${count} saved. ${(e as Error).message}`)}finally{setBusy(false)}}
 function stat(label:string,key:string,suffix=''){const v=exact?numeric(exact.data[key]):null;return <div className="suite-metric"><span>{label}</span><strong>{v===null?'—':v.toLocaleString()+suffix}</strong><small>{v===null?'No matching measurement':`${exact?.data.source||'User supplied'} · ${exact?.data.date||'undated'}`}</small></div>}
 return <div className="keyword-studio"><section className="suite-panel"><form className="keyword-search" onSubmit={e=>{e.preventDefault();setKeyword(input.trim());resetSelection();setPreferredSource('');setBrief('')}}><label>Keyword<div><Search size={17}/><input aria-label="Research keyword" maxLength={150} required value={input} onChange={e=>setInput(e.target.value)} placeholder="Enter a keyword to research"/></div></label><label>Country<input aria-label="Keyword country" required value={country} onChange={e=>{setCountry(e.target.value);resetSelection();setPreferredSource('')}}/></label><label>Language<input aria-label="Keyword language" required value={language} onChange={e=>{setLanguage(e.target.value);resetSelection();setPreferredSource('')}}/></label><button className="suite-primary">Explore keyword <ArrowRight size={16}/></button></form><div className="suite-note">Metrics come from your saved or imported keyword data in the selected market. Question and comparison suggestions are planning templates, not measured search demand or AI output.</div></section>
 {!keyword?<div className="suite-panel suite-empty"><Search size={28}/><h2>Turn a keyword into a content plan</h2><p>Explore measured data, question ideas, and existing page coverage. Save a shortlist and create an editable brief.</p></div>:<>
 <section className="suite-panel"><div className="suite-panelhead"><h2>Keyword overview: {keyword}</h2><button onClick={()=>onNavigate('seo','Keyword Research')}>Import or add metrics</button></div>{sources.length>1&&<div className="suite-toolbar"><label>Measurement source <select value={preferredSource} onChange={e=>setPreferredSource(e.target.value)}><option value="">Choose a source to show summary metrics</option>{sources.map(s=><option key={s}>{s}</option>)}</select></label></div>}<div className="suite-metrics">{stat('Monthly search volume','volume')}{stat('SEO difficulty','difficulty','/100')}{stat('CPC'+(exact?.data.currency?' ('+exact.data.currency+')':''),'cpc')}{stat('Paid difficulty','paidDifficulty','/100')}<div className="suite-metric"><span>Search intent</span><strong style={{fontSize:20}}>{exact?.data.intent||'—'}</strong><small>As supplied by your source</small></div></div><div className="suite-footer">No values are estimated from your page text. Use one provider consistently when comparing difficulty scores. Missing country or language on older records must be filled before they appear here.</div></section>
 <section className="suite-panel"><div className="suite-panelhead"><h2>Keyword ideas</h2><button disabled={!filtered.length} onClick={()=>exportText('keyword-ideas.csv',[['Keyword','Intent','Volume','SEO difficulty','CPC','Currency','Source','Date'],...filtered.map(r=>[r.term,r.intent,r.volume,r.difficulty,r.cpc,r.currency,r.source,r.date])].map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}><Download size={16}/> Export</button></div><div className="keyword-tabs" role="group" aria-label="Idea categories">{['Saved data','Questions','Comparisons','Modifiers'].map(c=><button aria-pressed={category===c} className={category===c?'selected':''} key={c} onClick={()=>{setCategory(c);setIntent('All');setMinVolume('');setMaxDifficulty('');resetSelection()}}>{c}</button>)}</div><div className="keyword-filters"><label>Intent<select value={intent} onChange={e=>{setIntent(e.target.value);resetSelection()}}>{['All','Informational','Commercial','Transactional','Navigational'].map(v=><option key={v}>{v}</option>)}</select></label><label>Minimum volume<input type="number" min="0" value={minVolume} onChange={e=>{setMinVolume(e.target.value);resetSelection()}}/></label><label>Maximum difficulty<input type="number" min="0" max="100" value={maxDifficulty} onChange={e=>{setMaxDifficulty(e.target.value);resetSelection()}}/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}>{['Keyword','Volume','Difficulty'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 <div className="suite-table"><Table><TableHeader><TableRow><TableHead><input type="checkbox" aria-label="Select all visible ideas" checked={filtered.length>0&&filtered.every(r=>selected.includes(r.term))} onChange={e=>setSelected(e.target.checked?[...new Set(filtered.map(r=>r.term))]:[])}/></TableHead>{['Keyword','Intent','Volume','Difficulty','Source'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map((r,i)=><TableRow key={r.term+r.source+i}><TableCell><input type="checkbox" aria-label={'Select '+r.term} checked={selected.includes(r.term)} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,r.term])]:s.filter(v=>v!==r.term))}/></TableCell><TableCell>{r.term}</TableCell><TableCell>{r.intent||'—'}</TableCell><TableCell>{r.volume?.toLocaleString()??'—'}</TableCell><TableCell>{r.difficulty??'—'}</TableCell><TableCell>{r.source}{r.date&&<small className="keyword-meta">{r.date}</small>}</TableCell></TableRow>)}</TableBody></Table></div>{!filtered.length&&<div className="suite-empty"><h2>No matching measurements</h2><p>Import keyword data, adjust the filters, or explore unmeasured question and comparison ideas.</p></div>}<div className="suite-toolbar"><label>Save to list <input aria-label="Keyword list name" maxLength={100} value={list} onChange={e=>setList(e.target.value)}/></label><button className="suite-primary" disabled={!selected.length||!list.trim()||!project||busy} onClick={saveSelected}><Plus size={16}/> {busy?'Saving…':`Save ${selected.length} selected`}</button></div><div className="suite-footer" role="status">{message||`${filtered.length} ideas · ${shortlist.length} saved keywords in this market`}</div></section>
 <div className="suite-columns"><section className="suite-panel"><div className="suite-panelhead"><h2>Existing page coverage</h2><span>{foundPages.length} matching pages</span></div>{foundPages.length?foundPages.map(p=><div className="suite-activity" key={p.url}><Check size={16}/><div><a href={p.url} target="_blank" rel="noreferrer">{p.title||p.url}</a><small>Exact phrase in {p.matches.join(', ')}</small></div></div>):<div className="suite-empty"><BookOpen size={25}/><p>{pages.length?'No exact phrase found in the crawled metadata. Review related pages before creating new content.':'Run a website audit to check page coverage.'}</p></div>}<div className="suite-footer">Uses only the current crawl's titles, H1s, H2s and descriptions. This is not a search ranking report or complete content-gap analysis.</div></section><section className="suite-panel"><div className="suite-panelhead"><h2>Plan your next page</h2></div><div className="suite-editor"><p>Create a brief grounded in this keyword, your supplied metrics, and matching pages.</p><button className="suite-primary" onClick={()=>setBrief(researchBrief(keyword,pages,exact?[exact]:[],country,language))}>Create content brief</button><p><button onClick={()=>onNavigate('seo','Keyword Lists')}>Open saved lists →</button></p></div></section></div>
 {brief&&<section className="suite-panel suite-editor"><h2>Editable content brief</h2><label>Brief<textarea rows={16} maxLength={8000} value={brief} onChange={e=>setBrief(e.target.value)}/></label><div className="suite-actions"><button onClick={()=>exportText('keyword-brief.md',brief)}>Download Markdown</button><button className="suite-primary" disabled={busy||!project||!brief.trim()} onClick={async()=>{setBusy(true);try{await onSave({title:'Brief: '+keyword,keyword,body:brief},'content');setMessage('Content brief saved in My Content.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Save to My Content</button></div><p role="status">{message}</p></section>}
 </>}
 </div>;
}
