'use client';
import {useEffect,useState} from 'react';
import type {Page,Issue} from '@/lib/crawler';
import './audit-report.css';
type Audit={pages:Page[],issues:Issue[],coverage?:string,created_at:string};
export default function SeoEvidenceReport({audit,selectedUrl}:{audit:Audit,selectedUrl?:string}){
 const [selected,setSelected]=useState(0),[expanded,setExpanded]=useState(false);
 useEffect(()=>{if(selectedUrl){const i=audit.pages.findIndex(p=>p.url===selectedUrl);if(i>=0)setSelected(i)}},[selectedUrl,audit]);
 const page=audit.pages[selected];if(!page)return null;
 const valid=audit.pages.filter(p=>!p.error&&p.status>=200&&p.status<400);
 const findings=audit.issues.filter(i=>i.urls.includes(page.url));
 const checks:[string,boolean,string][]=[['Page title',!!page.title,page.title||'No title found'],['Meta description',!!page.description,page.description||'No description found'],['Main heading',page.h1.length===1,`${page.h1.length} H1 headings observed. Multiple H1s are not automatically an SEO error.`],['Canonical declaration',!!page.canonical,page.canonical||'No canonical found; absence alone does not prevent indexing.'],['Indexation directives',page.indexable,page.robots.trim()||'No noindex directive observed. This does not confirm Google indexing.'],['Image alt attributes',page.missingAlt===0,`${page.missingAlt} of ${page.images} images lack an alt attribute. Empty alt attributes may be appropriate for decorative images.`],['Mobile viewport',page.viewport,page.viewport?'Viewport declaration present; layout has not been visually validated.':'No viewport declaration found.'],['Social preview title',page.og,page.og?'Open Graph title present.':'No Open Graph title found.']];
 const block=(title:string,children:React.ReactNode)=><section className="audit-block"><h3>{title}</h3>{children}</section>;
 const list=(values:string[])=>values.length?<ul className="seo-evidence-list">{values.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p>None observed in the fetched HTML.</p>;
 return <section className="audit-report seo-evidence"><header><div><small>GROWTHPILOT • OBSERVED HTML</small><h2>Detailed SEO report</h2><p>Inspect the evidence behind your audit, one page at a time.</p></div><button onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse checks':'Expand all checks'}</button></header>
 <div className="audit-meta"><span>{audit.coverage||'Limited HTML crawl'}</span><span>{new Date(audit.created_at).toLocaleString()}</span></div>
 <div className="audit-values seo-totals"><div><span>Successfully fetched HTML pages</span><strong>{valid.length} / {audit.pages.length}</strong></div><div><span>Issue categories across crawl</span><strong>{audit.issues.length}</strong></div><div><span>Pages with findings</span><strong>{audit.pages.filter(p=>audit.issues.some(i=>i.urls.includes(p.url))).length}</strong></div></div>
 <div className="audit-block"><label htmlFor="seo-evidence-page">Inspect a crawled page</label><select id="seo-evidence-page" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{audit.pages.map((p,i)=><option key={i} value={i}>{p.url}{p.error?' — fetch failed':''}</option>)}</select><p>HTTP {page.status||'unavailable'} · Crawl depth {page.depth} · {findings.length} issue categories for this page</p></div>
 {page.error||page.status>=400?<div className="audit-notice"><h3>Page could not be assessed</h3><p>{page.error||`HTTP ${page.status} was returned.`} Content checks below are unavailable for this page.</p></div>:<>
 {block('Search snippet preview',<><p>Illustration using your HTML metadata. Google may show different text.</p><div className="seo-snippet"><span>{page.url}</span><h4>{page.title||'No page title'}</h4><p>{page.description||'No meta description supplied.'}</p></div><p>Title: {page.title.length} characters · Description: {page.description.length} characters. Display width varies; these counts are not ranking factors.</p></>)}
 {block('On-page checks',<>{checks.map(([title,pass,evidence])=><details className="audit-finding" key={title+expanded+selected} open={expanded}><summary><span>{title}</span><small className={pass?'good':'warn'}>{pass?'✓ Check satisfied':'Review'}</small></summary><p>{evidence}</p></details>)}</>)}
 {block('Content & heading structure',<><div className="audit-values"><div><span>Observed word count</span><strong>{page.words}</strong></div><div><span>H1 headings</span><strong>{page.h1.length}</strong></div><div><span>H2 headings</span><strong>{page.h2.length}</strong></div></div><p>Text comes from paragraphs, lists and headings; nested elements can overlap. This is not a content-quality score.</p><h4>H1 headings</h4>{list(page.h1)}<h4>H2 headings</h4>{list(page.h2)}</>)}
 {block('Links discovered',<><p>Unique destinations per page; saved evidence is capped at 100 links per type in full-site crawls. These are outgoing links, not backlinks. Destinations have not all been checked for errors.</p><details className="audit-finding" open={expanded} key={'internal'+expanded+selected}><summary>Internal links ({page.internalLinks.length})</summary>{list(page.internalLinks)}</details><details className="audit-finding" open={expanded} key={'external'+expanded+selected}><summary>External links ({page.externalLinks.length})</summary>{list(page.externalLinks)}</details></>)}
 {block('Images & structured data',<><div className="audit-values"><div><span>Image elements</span><strong>{page.images}</strong></div><div><span>Missing alt attributes</span><strong>{page.missingAlt}</strong></div><div><span>JSON-LD blocks</span><strong>{page.schema}</strong></div></div><p>JSON-LD presence does not confirm valid structured data or eligibility for rich results. Other schema formats are not assessed.</p><details className="audit-finding" open={expanded} key={'images'+expanded+selected}><summary>Same-origin image URLs ({page.imageUrls?.length||0}, capped at 40)</summary>{list(page.imageUrls||[])}</details></>)}
 {block('Fetch & redirect evidence',<><p>HTML size: {(page.size/1024).toFixed(1)} KiB · Fetch duration: {page.responseTime} ms</p><p>Fetch duration is from the audit server, not browser load time or Core Web Vitals. HTML size excludes images, scripts and stylesheets.</p><h4>Redirect hops observed</h4>{list(page.redirects||[])}</>)}
 </>}
 {block('Recommended actions for this page',findings.length?<>{findings.map(i=><details className="audit-finding" key={i.title+expanded+selected} open={expanded}><summary>{i.title}<small>{i.severity}</small></summary><p>{i.why}</p><p><strong>Recommended fix: </strong>{i.fix}</p><p>Estimated effort: {i.effort} · Confidence: {i.confidence}</p></details>)}</>:<p>No findings from the checks performed. This is not a complete assessment of the page.</p>)}
 {block('Coverage & data sources',<><p>This report uses saved HTML from the crawl. See the coverage summary for its page limit and completeness. JavaScript is not rendered. Google PageSpeed measurements appear in their separate section above.</p><div className="seo-sources"><div><strong>Backlinks & domain authority</strong><span>Not measured — requires a backlink data provider.</span></div><div><strong>Search positions & query traffic</strong><span>Not measured here — requires Search Console or a ranking provider.</span></div><div><strong>Social audience & engagement</strong><span>Not measured — requires connected social accounts.</span></div><div><strong>Visual mobile usability & security</strong><span>Not validated by this HTML report.</span></div></div></>)}
 </section>
}

