'use client';
import {useState} from 'react';
import './seo-toolkit.css';
const escapeXml=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
export default function SeoToolkit({project,pages}:{project:{name:string,url:string}|null,pages:any[]}){
 const [tool,setTool]=useState('Meta checker'),[selected,setSelected]=useState(''),[description,setDescription]=useState(''),[source,setSource]=useState(''),[medium,setMedium]=useState(''),[campaign,setCampaign]=useState(''),[rules,setRules]=useState(''),[schemaType,setSchemaType]=useState('Organization'),[error,setError]=useState('');
 if(!project)return <section className="suite-panel suite-empty">Select or add a website to use the toolkit.</section>;
 const page=pages.find(p=>p.url===selected)||pages[0];
 const candidates=pages.filter(p=>{try{return !p.error&&p.status===200&&p.indexable&&new URL(p.url).origin===new URL(project.url).origin&&(!p.canonical||new URL(p.canonical,p.url).href===new URL(p.url).href)}catch{return false}});
 const urls=Array.from(new Set(candidates.map(p=>p.url as string)));
 function result(){if(tool==='Sitemap')return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+escapeXml(u)+'</loc></url>').join('\n')+'\n</urlset>';
 if(tool==='Robots.txt')return 'User-agent: *\n'+rules.split('\n').map(s=>s.trim()).filter(Boolean).map(s=>'Disallow: '+s).join('\n')+'\nSitemap: '+new URL('/sitemap.xml',project!.url).href+'\n';
 if(tool==='Schema')return JSON.stringify({'@context':'https://schema.org','@type':schemaType,name:project!.name,url:project!.url},null,2);
 if(tool==='UTM builder'){const u=new URL(project!.url);if(source)u.searchParams.set('utm_source',source);if(medium)u.searchParams.set('utm_medium',medium);if(campaign)u.searchParams.set('utm_campaign',campaign);return u.href}return description;}
 const output=result();
 function download(){setError('');if(tool==='Robots.txt'&&rules.split('\n').some(s=>s.trim()&&(!s.trim().startsWith('/')||/[\r#]/.test(s)))){setError('Use one path beginning with / per line, without comments.');return}const blob=new Blob([output],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=tool==='Sitemap'?'sitemap.xml':tool==='Robots.txt'?'robots.txt':tool==='Schema'?'schema.json':tool==='UTM builder'?'campaign-url.txt':'meta-description.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="suite-panel toolkit"><header><div><h2>SEO Toolkit</h2><p>Practical tools for {project.name}. Review generated files before adding them to your website.</p></div></header><nav aria-label="SEO tools">{['Meta checker','Description editor','Schema','Robots.txt','Sitemap','UTM builder'].map(t=><button key={t} aria-pressed={tool===t} onClick={()=>{setTool(t);setError('')}}>{t}</button>)}</nav><div className="toolkit-body">
 {['Meta checker','Description editor'].includes(tool)&&<label>Crawled page<select value={page?.url||''} onChange={e=>{setSelected(e.target.value);setDescription('')}}><option value="" disabled>Select a crawled page</option>{pages.map(p=><option key={p.url} value={p.url}>{p.url}</option>)}</select></label>}
 {tool==='Meta checker'&&(page?<><h3>Saved HTML observations</h3><p>These checks reflect the latest saved crawl, not a live recheck.</p><dl>{[['Title',page.title],['Description',page.description],['Canonical',page.canonical],['Robots',page.robots||'No directive observed'],['H1 headings',(page.h1||[]).join(' · ')],['Open Graph title',page.og?'Present':'Not observed']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not observed'}</dd></div>)}</dl></>:<p>Run a site audit to load page metadata.</p>)}
 {tool==='Description editor'&&<><p>Create an editable draft from the saved page description or title. This release uses a template, not AI generation.</p><button disabled={!page} onClick={()=>setDescription(page.description||page.title||'')}>Use page metadata</button><label>Meta description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label><small>{description.length} characters · Preview length varies by device and query.</small><article className="toolkit-preview"><small>{page?.url||project.url}</small><h3>{page?.title||project.name}</h3><p>{description||'Your description preview appears here.'}</p></article></>}
 {tool==='Schema'&&<><label>Schema type<select value={schemaType} onChange={e=>setSchemaType(e.target.value)}><option>Organization</option><option>WebSite</option></select></label><p>Basic markup using your project name and URL. Verify the business name and extend only with confirmed facts. This does not guarantee rich results.</p></>}
 {tool==='Robots.txt'&&<><label>Disallowed paths (one per line)<textarea rows={5} placeholder="/private/" value={rules} onChange={e=>setRules(e.target.value)}/></label><p>Empty rules allow crawling. A / rule blocks all paths. Robots rules do not protect private content or guarantee removal from search. Review your existing rules and sitemap location before replacing a file.</p></>}
 {tool==='Sitemap'&&<><h3>{urls.length} eligible URLs from the saved crawl</h3><p>Includes successful, indexable, same-origin pages with no conflicting canonical. A limited crawl produces a partial sitemap. Review this list before publishing.</p></>}
 {tool==='UTM builder'&&<div className="toolkit-fields">{[['Source',source,setSource],['Medium',medium,setMedium],['Campaign',campaign,setCampaign]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}</div>}
 {tool!=='Meta checker'&&<><label>Generated output<textarea readOnly rows={8} value={output}/></label><button disabled={!output||(tool==='Sitemap'&&!urls.length)||(tool==='UTM builder'&&(!source||!medium||!campaign))} onClick={download}>Download {tool==='UTM builder'?'campaign URL':'file'}</button></>}
 {error&&<p role="alert" className="suite-error">{error}</p>}</div></section>
}
