'use client';
import {useEffect,useRef,useState} from 'react';
import {House,Search,ChartNoAxesCombined,Sparkles,MapPin,FileText,Megaphone,MessagesSquare,Users,PanelsTopLeft,Plus,ArrowUpRight,RefreshCw,Download,Settings,CheckCircle2,ExternalLink,Trash2,Pencil,Menu,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {sections,recordTools,majorCountries,type Field} from '@/lib/suite';
import {validateRecord} from '@/lib/suite';
import {parseCsv} from '@/lib/csv';
import './suite.css';
import KeywordStudio from './keyword-studio';
import WebsiteImages from './website-images';
import AnalyticsPanel from './analytics-panel';
import AuditReport from './audit-report';
import SeoEvidenceReport from './seo-evidence-report';
type Project={id:string,name:string,url:string,country:string,language:string};
type RecordRow={id:string,kind:string,data:Record<string,string>,created_at:string,updated_at:string};
type Audit={id:string,score:number,created_at:string,pages:any[],issues:any[],scores:Record<string,number>,coverage?:string,performance?:any};
const icons=[House,Search,Sparkles,ChartNoAxesCombined,MapPin,FileText,Megaphone,MessagesSquare,Users,PanelsTopLeft,Settings];
async function api(path:string,method='GET',data?:unknown){const r=await fetch('/api/'+path,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error||'The request failed. Try again.');return d;}
function download(name:string,text:string,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function csv(rows:unknown[][]){return rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');}
function FieldInput({field,value,onChange}:{field:Field,value:string,onChange:(s:string)=>void}){const choices=field.key==='country'?majorCountries:field.key==='rankType'?['Country rank','Global rank','Industry rank']:[];return <label className={field.type==='textarea'?'wide':''}>{field.label}{field.required?' *':''}{field.type==='textarea'?<textarea required={field.required} maxLength={8000} value={value} onChange={e=>onChange(e.target.value)} rows={6}/>:choices.length?<select required={field.required} value={value} onChange={e=>onChange(e.target.value)}><option value="">Select {field.label.toLowerCase()}</option>{choices.map(c=><option value={c} key={c}>{c}</option>)}</select>:<input required={field.required} type={field.type||'text'} min={field.type==='number'?0:undefined} step={field.type==='number'?'any':undefined} maxLength={500} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
export default function SuiteWorkspace({signedIn=false}:{signedIn?:boolean}){
 const [researchQuery,setResearchQuery]=useState('');
 const [section,setSection]=useState('home'),[tool,setTool]=useState('Dashboard'),[nav,setNav]=useState(false);
 const [projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[audits,setAudits]=useState<Audit[]>([]),[records,setRecords]=useState<RecordRow[]>([]),[tasks,setTasks]=useState<any[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('');
 const [analyticsConnected,setAnalyticsConnected]=useState(false);
 const [projectModal,setProjectModal]=useState(false),[projectForm,setProjectForm]=useState({name:'',url:'',country:'United States',language:'English'});
 const [edit,setEdit]=useState<RecordRow|null|'new'>(null),[form,setForm]=useState<Record<string,string>>({}),[issue,setIssue]=useState<any>(null);
 const [draft,setDraft]=useState(''),[topic,setTopic]=useState(''),[content,setContent]=useState('');
 const requestId=useRef(0);const audit=audits[0],config=recordTools[tool];const current=sections.find(s=>s.id===section)!;
 useEffect(()=>{if(!nav)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setNav(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[nav]);
 function go(id:string,name?:string){setSection(id);setTool(name||sections.find(s=>s.id===id)!.tools[0]);setFilter('');setNav(false);setError('');}
 async function loadProject(p:Project){const seq=++requestId.current;setProject(p);setLoading(true);setAudits([]);setRecords([]);setTasks([]);setError('');try{const [d,r]=await Promise.all([api('projects/'+p.id),api('records?projectId='+p.id)]);if(seq===requestId.current){setAudits(d.audits);setTasks(d.tasks);setRecords(r.records)}}catch(e){if(seq===requestId.current)setError((e as Error).message)}finally{if(seq===requestId.current)setLoading(false)}}
 useEffect(()=>{let active=true;api('projects').then(d=>{if(!active)return;setProjects(d.projects);if(d.projects[0])void loadProject(d.projects[0]);else setLoading(false)}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false;requestId.current++}},[]);
 useEffect(()=>{if(tool!=='Data Sources'||!project)return;api('analytics?projectId='+encodeURIComponent(project.id)).then(d=>setAnalyticsConnected(!!d.connected)).catch(()=>setAnalyticsConnected(false))},[tool,project?.id]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message);toast.error((e as Error).message)}finally{setBusy(false)}}
 function runAudit(){if(!project){setProjectModal(true);return}const id=project.id,seq=requestId.current;void perform(async()=>{const d=await api('audit','POST',{projectId:id});if(requestId.current===seq)setAudits(a=>[d.audit,...a]);toast.success('Audit complete');go('seo','Site Audit')})}
 async function deleteWebsite(){if(!project)return;const target=project;if(!confirm(`Delete ${target.name} (${target.url}) permanently? This removes its audits, research, tasks and Analytics connection from GrowthPilot. Your actual website and Google Analytics property will not be deleted.`))return;await perform(async()=>{await api('projects/'+encodeURIComponent(target.id),'DELETE');const remaining=projects.filter(p=>p.id!==target.id);setProjects(remaining);requestId.current++;setProject(null);setAudits([]);setRecords([]);setTasks([]);setAnalyticsConnected(false);setLoading(false);if(remaining[0])await loadProject(remaining[0]);toast.success('Website deleted');})}
 async function createProject(e:React.FormEvent){e.preventDefault();await perform(async()=>{const d=await api('projects','POST',projectForm);setProjects(p=>[...p,d.project]);setProjectModal(false);await loadProject(d.project);toast.success('Website saved. Run your first audit.');})}
 async function save(e:React.FormEvent){e.preventDefault();if(!project||!config)return;await perform(async()=>{const data={projectId:project.id,kind:config.kind,data:form,...(edit&&edit!=='new'?{id:edit.id}:{})};await api('records',edit==='new'?'POST':'PATCH',data);const d=await api('records?projectId='+project.id);setRecords(d.records);setEdit(null);toast.success('Saved to your project')})}
 function openRecord(r?:RecordRow){if(!project){setProjectModal(true);return}setForm(r?r.data:{});setEdit(r||'new');}
 async function importCsv(file:File){if(!project||!config)return;await perform(async()=>{if(file.size>1000000)throw Error('Use a CSV smaller than 1 MB.');const rows=parseCsv(await file.text()),header=rows.shift();if(!header||!rows.length||rows.length>100)throw Error('Include a header and 1–100 data rows.');const columns=config.fields.map(f=>header.findIndex(h=>h.trim().toLowerCase()===f.label.toLowerCase()||h.trim().toLowerCase()===f.key));const missing=config.fields.filter((f,i)=>f.required&&columns[i]<0);if(missing.length)throw Error('Missing columns: '+missing.map(f=>f.label).join(', '));const data=rows.map((r,i)=>{try{return validateRecord(config.kind,Object.fromEntries(config.fields.map((f,j)=>[f.key,columns[j]>=0?r[columns[j]]||'':''])))}catch(e){throw Error(`Row ${i+2}: ${(e as Error).message}`)}});let saved=0;try{for(const entry of data){const d=await api('records','POST',{projectId:project.id,kind:config.kind,data:entry});setRecords(r=>[d.record,...r]);saved++}}catch(e){throw Error(`${saved} of ${data.length} records saved. ${(e as Error).message} Export existing records before retrying to avoid duplicates.`)}toast.success(`Imported ${saved} records`);})}
 function exportAudit(a:Audit){download('growthpilot-audit-'+a.created_at.slice(0,10)+'.csv',csv([['Website',project?.url],['Observed at',a.created_at],['Coverage',a.coverage],[],['Issue','Severity','Pages','Recommended fix'],...a.issues.map(i=>[i.title,i.severity,i.urls.join(' | '),i.fix])]),'text/csv;charset=utf-8')}
 const visibleRecords=records.filter(r=>r.kind===config?.kind&&Object.values(r.data).join(' ').toLowerCase().includes(filter.toLowerCase()));
 const pages=(audit?.pages||[]).filter(p=>`${p.url} ${p.title}`.toLowerCase().includes(filter.toLowerCase()));
 const issues=(audit?.issues||[]).filter(i=>`${i.title} ${i.severity}`.toLowerCase().includes(filter.toLowerCase()));
 function empty(title:string,description:string,action?:()=>void,label='Run audit'){return <div className="suite-empty"><Search size={30}/><h2>{title}</h2><p>{description}</p>{action&&<button className="suite-primary" onClick={action} disabled={busy}>{label}</button>}</div>}
 function metric(label:string,value:string|number,detail:string){return <div className="suite-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
 function table(headers:string[],rows:React.ReactNode[][]){return <div className="suite-table"><Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
 return <div className="suite"><Toaster richColors/><aside className={'suite-rail '+(nav?'open':'')}><a href="/" className="suite-brand" aria-label="GrowthPilot home">g<span>p</span></a>{sections.map((s,i)=>{const Icon=icons[i];return <button key={s.id} className={section===s.id?'active':''} onClick={()=>{const open=!(nav&&section===s.id);go(s.id);setNav(open)}} aria-expanded={nav&&section===s.id} aria-controls="suite-category-menu" title={s.label}><Icon size={21}/><span>{s.label}</span></button>})}</aside>
 {nav&&<button className="suite-menu-backdrop" aria-label="Dismiss menu" onClick={()=>setNav(false)}/>}<aside id="suite-category-menu" className={'suite-sidebar '+(nav?'open':'')}><div className="suite-side-title">{current.label}<button className="suite-mobile" onClick={()=>setNav(false)} aria-label="Close menu"><X/></button></div><p>{current.description}</p><nav aria-label={current.label}>{current.tools.map(name=><button key={name} className={tool===name?'selected':''} onClick={()=>go(section,name)}>{name}<span>›</span></button>)}</nav><div className="suite-side-bottom"><span className="suite-badge">REAL DATA WORKSPACE</span><p>Audits use observed HTML. Research and planning records are saved to your account.</p><button onClick={()=>go('apps')}>Manage data sources <ArrowUpRight size={15}/></button></div></aside>
 <div className="suite-main"><header className="suite-top"><button className="suite-mobile" onClick={()=>setNav(true)} aria-label="Open menu"><Menu/></button><form onSubmit={e=>{e.preventDefault();const found=projects.find(p=>p.url.toLowerCase().includes(query.toLowerCase()));if(found&&query){void loadProject(found);go('seo','Site Audit')}else if(query.includes('.')){setProjectForm(f=>({...f,url:query}));setProjectModal(true)}else{setResearchQuery(query.trim());go('seo','Keyword Overview')}}}><Search size={17}/><input aria-label="Website or keyword" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Enter website or keyword" required/><button type="submit">Analyze</button></form><div className="suite-account">{signedIn?<span><CheckCircle2 size={15}/> Private workspace</span>:<a href="/signin-with-chatgpt?return_to=%2F">Sign in</a>}<span className="suite-avatar">GP</span></div></header>
 <main className="suite-body"><div className="suite-heading"><div><div className="suite-breadcrumb">GrowthPilot / {current.label}</div><h1>{tool}</h1><p>{config?.description||current.description}</p></div><div className="suite-actions"><select aria-label="Current website" value={project?.id||''} disabled={busy} onChange={e=>{const p=projects.find(p=>p.id===e.target.value);if(p)void loadProject(p)}}><option value="" disabled>Select website</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button onClick={()=>setProjectModal(true)}><Plus size={16}/> Website</button><button disabled={!project||busy||loading} onClick={()=>void deleteWebsite()} aria-label="Delete selected website"><Trash2 size={16}/> Delete website</button></div></div>
 {error&&<div className="suite-error" role="alert">{error}</div>}{!signedIn&&<div className="suite-note">Sign in to save websites, run audits, and access your private research.</div>}
 {loading?<div className="suite-empty" role="status">Loading your workspace…</div>:<>
 {tool==='Keyword Overview'&&<KeywordStudio key={(project?.id||'none')+':'+researchQuery} project={project} records={records} pages={audit?.pages||[]} initialKeyword={researchQuery} onNavigate={go} onSave={async(data,kind)=>{if(!project)throw Error('Add a website first.');const d=await api('records','POST',{projectId:project.id,kind,data});setRecords(r=>[d.record,...r]);toast.success('Saved to your project')}}/>}
 {tool==='Dashboard'&&<><div className="suite-toolcards">{sections.slice(1,7).map((s,i)=>{const Icon=icons[i+1];return <button key={s.id} onClick={()=>go(s.id)}><span className={'suite-toolicon color-'+i}><Icon size={21}/></span><strong>{s.label}</strong><p>{s.description}</p><span className="suite-card-link">Open workspace →</span></button>})}</div><section className="suite-panel"><div className="suite-panelhead"><h2>Your website</h2><button className="suite-primary" disabled={busy} onClick={runAudit}><RefreshCw size={15}/>{busy?'Auditing…':'Run audit'}</button></div>{project?<><div className="suite-domain"><span className="suite-domainicon">{project.name[0]}</span><strong>{project.name}</strong><a href={project.url} target="_blank" rel="noreferrer">{new URL(project.url).hostname}<ExternalLink size={12}/></a></div><div className="suite-metrics">{metric('HTML audit score',audit?audit.score+'/100':'—',audit?'Observed HTML checks':'Run your first audit')}{metric('Pages checked',audit?.pages.length??'—','Up to 10 pages per audit')}{metric('Issue categories',audit?.issues.length??'—','Evidence and recommended fixes')}{metric('Saved research',records.length,'Your project records')}{metric('Open actions',tasks.filter(t=>!['Completed','Ignored'].includes(t.status)).length,'From your audit findings')}</div>{audit&&<div className="suite-footer">Last audit: {new Date(audit.created_at).toLocaleString()} · {audit.coverage}</div>}</>:empty('Add your first website','Enter a public website to begin analyzing its actual pages.',()=>setProjectModal(true),'Add website')}</section><div className="suite-columns"><section className="suite-panel"><div className="suite-panelhead"><h2>Priority findings</h2><button onClick={()=>go('seo','Site Audit')}>View audit →</button></div>{audit?.issues.length?audit.issues.slice(0,4).map(i=><button className="suite-finding" key={i.title} onClick={()=>setIssue(i)}><span className={'suite-severity '+i.severity}>{i.severity}</span><strong>{i.title}</strong><small>{i.urls.length} pages →</small></button>):empty('No findings yet','Run an audit to see observed issues.')}</section><section className="suite-panel"><div className="suite-panelhead"><h2>Recent activity</h2></div>{records.slice(0,5).map(r=><div className="suite-activity" key={r.id}><FileText size={18}/><div><strong>{r.data.title}</strong><small>{r.kind} · {new Date(r.updated_at).toLocaleDateString()}</small></div></div>)}{!records.length&&empty('Your work starts here','Save a keyword, draft, or campaign to build your project history.')}</section></div></>}
 {tool==='Site Audit'&&audit&&project&&<AuditReport key={audit.id} performance={audit.performance} url={project.url}/>} 
 {tool==='Site Audit'&&<section className="suite-panel"><div className="suite-panelhead"><h2>{project?.url||'Website audit'}</h2><button className="suite-primary" onClick={runAudit} disabled={busy}>{busy?'Auditing…':'Run new audit'}</button></div>{audit?<><div className="suite-metrics">{metric('HTML audit score',audit.score+'/100','Diagnostic score, not a ranking prediction')}{Object.entries(audit.scores).map(([key,value])=><div key={key}>{metric(key,value+'/100','Observed HTML checks')}</div>)}</div><div className="suite-toolbar"><input aria-label="Filter audit issues" placeholder="Filter issues or severity" value={filter} onChange={e=>setFilter(e.target.value)}/><button onClick={()=>exportAudit(audit)}><Download size={16}/> Export audit</button></div>{table(['Issue','Severity','Affected pages',''],issues.map(i=>[<button className="suite-link" onClick={()=>setIssue(i)}>{i.title}</button>,<span className={'suite-severity '+i.severity}>{i.severity}</span>,i.urls.length,<button onClick={()=>setIssue(i)}>Review →</button>]))}<div className="suite-footer">{audit.coverage} · {new Date(audit.created_at).toLocaleString()} · JavaScript is not rendered.</div></>:empty('Discover what needs attention','We inspect titles, headings, descriptions, indexing directives, images, and other on-page signals.',runAudit)}</section>}
 {tool==='Site Audit'&&audit&&<SeoEvidenceReport key={audit.id} audit={audit}/>} 
 {tool==='Top Pages'&&<section className="suite-panel"><div className="suite-panelhead"><h2>Crawled pages</h2><input aria-label="Filter pages" placeholder="Search page URL or title" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{audit?table(['URL / title','HTTP status','Words','Missing alt','Indexable'],pages.map(p=>[<div className="suite-url"><a href={p.url} target="_blank" rel="noreferrer">{p.url}</a><small>{p.title||p.error||'No title'}</small></div>,p.status||'Failed',p.words,p.missingAlt,p.indexable?'Yes':'No'])):empty('No crawled pages yet','Run an audit to inspect your real page inventory.',runAudit)}</section>}
 {tool==='Action Plan'&&<section className="suite-panel"><div className="suite-panelhead"><h2>Audit actions</h2><button onClick={()=>go('seo','Site Audit')}>Add from findings →</button></div>{tasks.length?table(['Task','Priority','Status'],tasks.map(t=>[t.title,t.priority,<select aria-label={'Status for '+t.title} value={t.status} disabled={busy} onChange={e=>{const status=e.target.value;void perform(async()=>{await api('tasks','PATCH',{projectId:project!.id,id:t.id,status});setTasks(ts=>ts.map(x=>x.id===t.id?{...x,status}:x))})}}>{['Open','In Progress','Completed','Ignored'].map(s=><option key={s}>{s}</option>)}</select>])):empty('No saved actions','Open an audit finding and add it to your action plan.')}</section>}
 {config&&<section className="suite-panel">{config.source&&<div className="suite-note">{config.source}</div>}{tool==='Country Rankings'&&<div className="country-strip"><strong>Major markets</strong>{majorCountries.slice(0,10).map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(filter===c?'':c)}>{c}</button>)}</div>}<div className="suite-toolbar"><input aria-label="Search saved records" placeholder="Search saved records" value={filter} onChange={e=>setFilter(e.target.value)}/><div><button disabled={!project||busy} onClick={()=>download(config.kind+'-template.csv',csv([config.fields.map(f=>f.label)]),'text/csv;charset=utf-8')}>CSV template</button><label className="suite-import">Import CSV<input aria-label="Import CSV" type="file" accept=".csv,text/csv" disabled={!project||busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importCsv(file)}}/></label><button disabled={!visibleRecords.length} onClick={()=>download(config.kind+'.csv',csv([config.fields.map(f=>f.label),...visibleRecords.map(r=>config.fields.map(f=>r.data[f.key]))]),'text/csv;charset=utf-8')}><Download size={16}/> Export CSV</button><button className="suite-primary" onClick={()=>openRecord()}><Plus size={16}/> Add record</button></div></div>{visibleRecords.length?table([config.fields[0].label,...config.fields.slice(1,3).map(f=>f.label),...(tool==='Country Rankings'?['Rank','Visits','Traffic share']:[]),'Updated','Actions'],visibleRecords.map(r=>[<button className="suite-link" onClick={()=>openRecord(r)}>{r.data.title}</button>,...config.fields.slice(1,3).map(f=><span className="suite-truncate">{r.data[f.key]||'—'}</span>),...(tool==='Country Rankings'?[r.data.rank||'—',r.data.visits||'—',r.data.share?`${r.data.share}%`:'—']:[]),new Date(r.updated_at).toLocaleDateString(),<div className="suite-rowactions"><button aria-label={'Edit '+r.data.title} onClick={()=>openRecord(r)}><Pencil size={15}/></button><button disabled={busy} aria-label={'Delete '+r.data.title} onClick={()=>{if(!confirm('Delete this saved record?'))return;void perform(async()=>{await api('records','DELETE',{id:r.id,projectId:project!.id});setRecords(rs=>rs.filter(x=>x.id!==r.id))})}}><Trash2 size={15}/></button></div>])):empty(filter?'No matching records':'No records yet',filter?'Try a different search.':'Add your first record. It will be saved privately to this website.',()=>openRecord(),'Add record')}<div className="suite-footer">{visibleRecords.length} records · User-supplied data · Saved on the server</div></section>}
 {tool==='SEO Brief Generator'&&<section className="suite-panel suite-editor"><h2>Create a crawl-informed brief</h2><p>This tool builds an editable outline from your topic and observed site issues. It does not use an AI model.</p><label>Topic / primary keyword<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What should the page help someone do?"/></label><button className="suite-primary" disabled={!topic.trim()||!audit} onClick={()=>setDraft(`# ${topic.trim()}\n\nWebsite: ${project?.url}\nAudit date: ${audit?.created_at}\n\nAudience and intent\n[Describe the intended reader and the question this page answers.]\n\nSuggested outline\n- What is ${topic.trim()}?\n- When is it useful?\n- Practical steps and examples\n- Common questions\n\nObserved improvements to consider\n${audit?.issues.filter(i=>['Content','SEO'].includes(i.category)).map(i=>'- '+i.title+': '+i.fix).join('\n')}\n\nInternal links to review\n${audit?.pages.filter(p=>!p.error).slice(0,5).map(p=>'- '+p.url).join('\n')}\n\nEvidence required\n[Add original research, sources, and verified examples before publishing.]`)}>Build brief</button>{!audit&&<p>Run a website audit first to supply page evidence.</p>}<label>Editable brief<textarea rows={18} value={draft} onChange={e=>setDraft(e.target.value)}/></label><div className="suite-actions"><button disabled={!draft} onClick={()=>download('seo-brief.md',draft)}>Download Markdown</button><button disabled={!draft||!project||busy} onClick={()=>void perform(async()=>{const d=await api('records','POST',{projectId:project!.id,kind:'content',data:{title:topic,keyword:topic,body:draft}});setRecords(r=>[d.record,...r]);toast.success('Saved in My Content')})}>Save to My Content</button></div></section>}
 {tool==='Content Optimizer'&&<section className="suite-panel suite-editor"><h2>Inspect your draft</h2><p>Check word count and keyword usage. These checks do not predict rankings or establish content quality.</p><label>Target phrase<input value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Draft content<textarea rows={14} value={content} onChange={e=>setContent(e.target.value)}/></label><div className="suite-metrics">{metric('Words',content.trim()?content.trim().split(/\s+/).length:0,'Whitespace-separated words')}{metric('Target phrase mentions',topic.trim()?content.toLowerCase().split(topic.trim().toLowerCase()).length-1:'—','Exact phrase occurrences')}{metric('Paragraphs',content.trim()?content.trim().split(/\n\s*\n/).length:0,'Separated by blank lines')}</div><button disabled={!content||!project||busy} className="suite-primary" onClick={()=>void perform(async()=>{const d=await api('records','POST',{projectId:project!.id,kind:'content',data:{title:topic||'Untitled draft',keyword:topic,body:content}});setRecords(r=>[d.record,...r]);toast.success('Draft saved')})}>Save draft</button></section>}
 {tool==='Audit Reports'&&<section className="suite-panel"><div className="suite-panelhead"><h2>Audit history</h2><span>Observed website data</span></div>{audits.length?table(['Date','Health score','Pages','Issues','Download'],audits.map(a=>[new Date(a.created_at).toLocaleString(),a.score+'/100',a.pages.length,a.issues.length,<button onClick={()=>exportAudit(a)}><Download size={16}/> CSV</button>])):empty('No reports yet','Completed audits appear here automatically.',runAudit)}</section>}
 {project&&['Data Sources','Website Performance'].includes(tool)&&<AnalyticsPanel key={project.id} projectId={project.id}/>} 
 {tool==='Data Sources'&&<section className="suite-panel"><div className="suite-panelhead"><h2>Source availability</h2></div>{table(['Source','Used for','Status'],[['Website crawler','On-page SEO, page inventory, audit reports','Available — run an audit'],['Google PageSpeed Insights','Mobile and desktop performance','Public API; subject to provider quota'],['Google Analytics 4','Traffic and engagement',<><span>{analyticsConnected?'Connected — Google OAuth authorized':'Not connected — connect below'}</span> <button onClick={async()=>{if(!project){alert('Select a website first.');return}const r=await fetch('/api/analytics?projectId='+encodeURIComponent(project.id),{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(d.url)window.location.href=d.url;else alert(d.error||'Google Analytics is unavailable.')}}>{analyticsConnected?'Reconnect':'Connect'}</button></>],['Google Search Console','Queries, clicks, impressions','Not connected — manual records available'],['Search / backlink provider','SERP positions, search volume, backlinks','Not connected — manual research available'],['AI model provider','Generated articles and automated prompt checks','Not connected — brief templates and observations available'],['Google Business Profile','Listings, reviews, map visibility','Not connected — local planning available'],['Ads, social, and email accounts','Campaign delivery, post publishing, outreach','Not connected — drafts and planning only']])}<div className="suite-note">No provider credentials are configured through this screen. External account connections and automated synchronization still need implementation and access to your providers. Never put API keys in research notes.</div></section>}
 {['Dashboard','Top Pages','Website Performance'].includes(tool)&&<WebsiteImages pages={audit?.pages||[]} onAudit={runAudit} busy={busy}/>}
 </>}
 </main></div>
 <Dialog open={projectModal} onOpenChange={setProjectModal}><DialogContent className="suite-dialog"><DialogTitle>Add your website</DialogTitle><DialogDescription>Create a real website project. Your workspace supports up to 20 websites.</DialogDescription><form onSubmit={createProject}><div className="suite-fields">{(['name','url','country','language'] as const).map(key=><FieldInput key={key} field={{key,label:({name:'Project name',url:'Website URL',country:'Target country',language:'Language'})[key],required:true,type:key==='url'?'url':undefined}} value={projectForm[key]} onChange={value=>setProjectForm(f=>({...f,[key]:value}))}/>)}</div>{error&&<p role="alert" className="suite-error">{error}</p>}<button className="suite-primary" disabled={busy}>{busy?'Saving…':'Create project'}</button></form></DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={open=>{if(!open)setEdit(null)}}><DialogContent className="suite-dialog"><DialogTitle>{edit==='new'?'Add':'Edit'} {tool.toLowerCase()} record</DialogTitle><DialogDescription>{config?.description}</DialogDescription><form onSubmit={save}><div className="suite-fields">{config?.fields.map(field=><FieldInput key={field.key} field={field} value={form[field.key]||''} onChange={value=>setForm(f=>({...f,[field.key]:value}))}/>)}</div>{error&&<p role="alert" className="suite-error">{error}</p>}<button className="suite-primary" disabled={busy}>{busy?'Saving…':'Save record'}</button></form></DialogContent></Dialog>
 <Dialog open={!!issue} onOpenChange={open=>{if(!open)setIssue(null)}}><DialogContent className="suite-dialog"><DialogTitle>{issue?.title}</DialogTitle><DialogDescription>{issue?.why}</DialogDescription><h3>Recommended fix</h3><p>{issue?.fix}</p><h3>Observed on</h3><ul>{issue?.urls.map((url:string)=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ul><button className="suite-primary" disabled={busy||!project} onClick={()=>void perform(async()=>{const d=await api('tasks','POST',{projectId:project!.id,title:issue.title,priority:issue.severity,url:issue.urls[0]||''});setTasks(t=>t.some(x=>x.id===d.task.id)?t:[d.task,...t]);setIssue(null);toast.success('Added to action plan')})}>Add to action plan</button></DialogContent></Dialog>
 </div>;
}






