import {load} from 'cheerio/slim';
export type Page={url:string,status:number,title:string,description:string,h1:string[],h2:string[],canonical:string,robots:string,indexable:boolean,words:number,internalLinks:string[],externalLinks:string[],images:number,imageUrls:string[],missingAlt:number,schema:number,viewport:boolean,og:boolean,responseTime:number,size:number,depth:number,redirects:string[],error?:string};
export type Issue={title:string,severity:string,category:string,why:string,fix:string,urls:string[],effort:string,confidence:string};
const AGENT='GrowthPilotBot';
export function validateUrl(raw:string){const u=new URL(raw.includes('://')?raw:'https://'+raw);const h=u.hostname.toLowerCase();if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!h.includes('.')||h.endsWith('.')||/^[\d.]+$/.test(h)||h.includes(':')||/(^|\.)(localhost|local|internal|test|invalid|example|lan|home|onion)$/.test(h))throw Error('Enter a public website URL using HTTP or HTTPS, without a custom port or credentials.');u.hash='';return u}
function publicIPv4(ip:string){if(!/^\d+\.\d+\.\d+\.\d+$/.test(ip))return false;const [a,b,c]=ip.split('.').map(Number);return ![0,10,127].includes(a)&&a<224&&!(a===169&&b===254)&&!(a===172&&b>=16&&b<=31)&&!(a===192&&(b===168||b===0||b===2))&&!(a===100&&b>=64&&b<=127)&&!(a===198&&(b===18||b===19||b===51&&c===100))&&!(a===203&&b===0&&c===113)}
export async function publicHost(host:string){const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(host)+'&type=A',{headers:{Accept:'application/dns-json'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Could not verify public website DNS. Try again later.');const data:any=await r.json();const addresses=(data.Answer||[]).filter((x:any)=>x.type===1).map((x:any)=>x.data);if(!addresses.length||addresses.some((a:string)=>!publicIPv4(a)))throw Error('This website must resolve to a public internet address.');}
async function limitedText(r:Response,max=1500000){if(Number(r.headers.get('content-length')||0)>max){await r.body?.cancel();throw Error('Page exceeds the audit size limit.')}if(!r.body)return '';const reader=r.body.getReader();let n=0,out='';const decoder=new TextDecoder();try{while(true){const chunk=await reader.read();if(chunk.done)break;n+=chunk.value.length;if(n>max)throw Error('Page exceeds the audit size limit.');out+=decoder.decode(chunk.value,{stream:true})}return out+decoder.decode()}finally{await reader.cancel().catch(()=>{})}}
async function requestPage(url:string,origin:string,policy?:Rule[]){let current=url;const redirects:string[]=[];for(let i=0;i<5;i++){const u=validateUrl(current);if(policy&&!allowed(u.pathname+u.search,policy))throw Error('Redirect destination is blocked by robots.txt.');if(u.origin!==origin)throw Error('Redirect leaves the selected origin. Add the final website URL instead.');const r=await fetch(u.href,{redirect:'manual',headers:{'User-Agent':AGENT+'/1.0 (+SEO audit)','Accept':'text/html,application/xhtml+xml,text/plain,application/xml'},signal:AbortSignal.timeout(8000)});if([301,302,303,307,308].includes(r.status)){const location=r.headers.get('location');await r.body?.cancel();if(!location)throw Error('Redirect has no destination.');redirects.push(current);current=new URL(location,current).href;continue}return {r,url:current,redirects}}throw Error('Redirect chain exceeds 5 hops.')}
type Rule={path:string,allow:boolean};
export function robotsRules(text:string){const groups:{agents:string[],rules:Rule[]}[]=[];let group={agents:[] as string[],rules:[] as Rule[]};for(const line of text.split(/\r?\n/)){const clean=line.split('#')[0].trim();const split=clean.indexOf(':');if(split<0)continue;const key=clean.slice(0,split).trim().toLowerCase(),value=clean.slice(split+1).trim();if(key==='user-agent'){if(group.rules.length){groups.push(group);group={agents:[],rules:[]}}group.agents.push(value.toLowerCase())}else if((key==='allow'||key==='disallow')&&group.agents.length&&value)group.rules.push({path:value,allow:key==='allow'})}groups.push(group);const exact=groups.filter(g=>g.agents.some(a=>a!=='*'&&AGENT.toLowerCase().includes(a)));return (exact.length?exact:groups.filter(g=>g.agents.includes('*'))).flatMap(g=>g.rules)}
export function allowed(path:string,rules:Rule[]){let best:Rule|undefined;for(const r of rules){const end=r.path.endsWith('$');const pattern=r.path.replace(/\$$/,'').split('*').map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('.*');if(new RegExp('^'+pattern+(end?'$':'')).test(path)&&(!best||r.path.length>best.path.length||r.path.length===best.path.length&&r.allow))best=r}return !best||best.allow}
async function parsePage(html:string,url:string,status:number,ms:number,depth:number,redirects:string[],xrobots:string):Promise<Page>{
 const $=load(html);const links:string[]=[];$('a[href]').each((_,e)=>{try{const u=new URL($(e).attr('href')!,url);u.hash='';if(['http:','https:'].includes(u.protocol)&&!links.includes(u.href)&&links.length<1000)links.push(u.href)}catch{}});const origin=new URL(url).origin;const imageUrls:string[]=[];$('img[src]').each((_,e)=>{try{const src=$(e).attr('src')!;if(src.startsWith('data:'))return;const u=new URL(src,url);u.hash='';if(u.protocol.startsWith('http')&&u.origin===origin&&!imageUrls.includes(u.href)&&imageUrls.length<40)imageUrls.push(u.href)}catch{}});
 const robots=xrobots+' '+($('meta[name="robots" i]').attr('content')||'');const words=$('p,li,h1,h2,h3,h4,h5,h6').map((_,e)=>$(e).text()).get().join(' ').trim();
 return {url,status,title:$('title').first().text().trim(),description:$('meta[name="description" i]').attr('content')||'',h1:$('h1').map((_,e)=>$(e).text().trim()).get(),h2:$('h2').map((_,e)=>$(e).text().trim()).get(),canonical:$('link[rel="canonical" i]').attr('href')||'',robots,indexable:status>=200&&status<300&&!/\b(noindex|none)\b/i.test(robots),words:words?words.split(/\s+/).length:0,internalLinks:links.filter(u=>new URL(u).origin===origin),externalLinks:links.filter(u=>new URL(u).origin!==origin),images:$('img').length,imageUrls,missingAlt:$('img:not([alt])').length,schema:$('script[type="application/ld+json"]').length,viewport:$('meta[name="viewport" i]').length>0,og:$('meta[property="og:title"]').length>0,responseTime:ms,size:new TextEncoder().encode(html).length,depth,redirects};
}export function analyze(pages:Page[],site:{robots:boolean,sitemap:boolean}){const issues:Issue[]=[];const add=(title:string,severity:string,category:string,matched:Page[],why:string,fix:string,effort='15–30 min',confidence='High')=>{if(matched.length)issues.push({title,severity,category,urls:matched.map(p=>p.url),why,fix,effort,confidence})};const html=pages.filter(p=>!p.error&&p.status<400);
add('Repair unavailable pages','Critical','Technical SEO',pages.filter(p=>p.status>=400),'The crawler received an HTTP error. Visitors and search engines may not reach the intended content.','Restore the intended content or update links to a relevant live page.');
add('Review pages that could not be fetched','High','Technical SEO',pages.filter(p=>!!p.error),'Some requests could not be completed. A timeout, access policy, or redirect may be responsible. These pages are excluded from content scoring.','Inspect the page and hosting logs. Confirm the final URL and crawler access before retrying.');
add('Add missing page titles','High','SEO',html.filter(p=>!p.title),'A title gives people and search engines a concise description of the page.','Write a unique title aligned with the primary intent of each page.');
add('Write unique meta descriptions','Medium','SEO',html.filter(p=>!p.description),'Without a description, you have less control over the snippet search engines may display.','Write a concise description explaining the page’s value. Search engines may still choose a different snippet.');
add('Review long page titles','Low','SEO',html.filter(p=>p.title.length>65),'Long titles may be truncated. Character count is only a rough guide, not a pixel-width measurement.','Move the clearest description to the beginning. Preview titles on mobile and desktop.');
add('Review duplicate titles','Medium','SEO',html.filter(p=>p.title&&html.filter(x=>x.title===p.title).length>1),'Multiple crawled pages share a title, making their purpose harder to distinguish.','Create a specific title for each distinct intent. Review duplicates before choosing canonicals or redirects.');
add('Clarify the main page heading','Medium','Content',html.filter(p=>p.h1.length!==1),'A clear main heading helps visitors understand the page. Multiple H1s are not automatically an SEO error.','Ensure the primary topic has a clear main heading and supporting headings form a useful hierarchy.');
add('Review indexation directives','High','Technical SEO',html.filter(p=>!p.indexable),'A noindex directive was observed. This may be intentional and does not prove an indexing problem.','Confirm whether these pages should appear in search. Remove noindex only on pages intended to be indexed.','15 min','Medium');
add('Review missing canonical tags','Medium','Technical SEO',html.filter(p=>!p.canonical),'An explicit canonical can clarify the preferred URL when duplicate variants exist. Its absence alone does not prevent indexing.','Check for duplicate variants, then add a correct canonical where useful.');
add('Add appropriate image alternatives','Medium','Content',html.filter(p=>p.missingAlt>0),'Images are missing alt attributes, which can reduce accessibility and image context.','Use descriptive alt text for informative images and an empty alt attribute for decorative images.');
add('Add a mobile viewport declaration','High','Technical SEO',html.filter(p=>!p.viewport),'Without a viewport declaration, a page may display at a desktop width on mobile.','Add a width=device-width, initial-scale=1 viewport meta tag and test on mobile.');
add('Review pages with limited visible text','Opportunity','Content',html.filter(p=>p.words<200),'Less than 200 words were observed in paragraphs, lists, and headings. Short content is not inherently low quality; JavaScript content is not rendered in this crawl.','Check whether each page fully satisfies its intent before expanding it.','1–2 hours','Medium');
add('Review structured data opportunities','Opportunity','Content',html.filter(p=>!p.schema),'No JSON-LD block was found. Other structured-data formats were not validated.','Consider relevant schema supported by the page content. Validate it before publication.','30–60 min','Medium');
add('Add social preview metadata','Low','SEO',html.filter(p=>!p.og),'No Open Graph title was observed. Shared links may have less predictable previews.','Add an Open Graph title and description matching the page.');
if(!site.sitemap)add('Review sitemap availability','Opportunity','Technical SEO',html.slice(0,1),'No XML sitemap was found at /sitemap.xml. A sitemap may exist elsewhere.','Check robots.txt for a sitemap location and confirm it contains canonical, indexable URLs.');
const order:Record<string,number>={Critical:0,High:1,Medium:2,Low:3,Opportunity:4};issues.sort((a,b)=>order[a.severity]-order[b.severity]);
const ratio=(fn:(p:Page)=>boolean)=>html.length?Math.round(100*html.filter(fn).length/html.length):0;
const scores={SEO:Math.round((ratio(p=>!!p.title)+ratio(p=>!!p.description)+ratio(p=>p.title.length<=65))/3),'Technical SEO':Math.round((ratio(p=>p.indexable)+ratio(p=>!!p.canonical)+ratio(p=>p.viewport))/3),Content:Math.round((ratio(p=>p.h1.length===1)+ratio(p=>p.missingAlt===0))/2)};
return {issues,scores,score:Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/3)} }
export async function crawl(raw:string){const start=validateUrl(raw);await publicHost(start.hostname);const robots=await requestPage(start.origin+'/robots.txt',start.origin);let rules:Rule[]=[];if(robots.r.status===200)rules=robotsRules(await limitedText(robots.r,500000));else{await robots.r.body?.cancel();if(robots.r.status!==404&&robots.r.status!==410)throw Error('Robots policy could not be verified. The crawl was not started.')}if(!allowed(start.pathname+start.search,rules))throw Error('This website’s robots.txt disallows the requested crawl.');const queue=[{url:start.href,depth:0}],seen=new Set<string>(),pages:Page[]=[];const began=Date.now();let stopped=false;
while(queue.length&&pages.length<10){if(Date.now()-began>45000){stopped=true;break}const next=queue.shift()!;if(seen.has(next.url))continue;seen.add(next.url);const target=new URL(next.url);if(!allowed(target.pathname+target.search,rules))continue;const at=Date.now();try{const result=await requestPage(next.url,start.origin,rules),type=result.r.headers.get('content-type')||'';if(!type.includes('text/html')&&!type.includes('application/xhtml+xml')){await result.r.body?.cancel();continue}const html=await limitedText(result.r);const page=await parsePage(html,result.url,result.r.status,Date.now()-at,next.depth,result.redirects,result.r.headers.get('x-robots-tag')||'');pages.push(page);if(page.status<400&&!/\b(nofollow|none)\b/i.test(page.robots)){for(const link of page.internalLinks){const u=new URL(link);if(queue.length<100&&!seen.has(link)&&u.origin===start.origin&&!u.search&&!/\.(pdf|jpe?g|png|gif|svg|zip|mp4|css|js|webp)$/i.test(u.pathname))queue.push({url:link,depth:next.depth+1})}}}catch(error){pages.push({url:next.url,status:0,error:error instanceof Error?error.message:'Request failed',title:'',description:'',h1:[],h2:[],canonical:'',robots:'',indexable:false,words:0,internalLinks:[],externalLinks:[],images:0,imageUrls:[],missingAlt:0,schema:0,viewport:false,og:false,responseTime:Date.now()-at,size:0,depth:next.depth,redirects:[]})}}
if(!pages.some(p=>!p.error&&p.status<400))throw Error(pages[0]?.error||'No accessible HTML pages could be audited.');let sitemap=false;try{const s=await requestPage(start.origin+'/sitemap.xml',start.origin);sitemap=s.r.ok&&/<(urlset|sitemapindex)\b/.test(await limitedText(s.r,500000))}catch{}const result=analyze(pages,{robots:robots.r.status===200,sitemap});return {...result,pages,coverage:`${pages.length}/10-page limit · ${stopped?'time limit reached':queue.length?'partial website crawl':'discovered pages checked'} · HTML only`,source:'Observed HTML crawl; deterministic recommendations',limitations:['No JavaScript rendering','No search ranking or traffic data','No external backlink or schema validation','Only same-origin links without query parameters are followed','Scores are diagnostic, not predictions of search performance']}}



