import {env} from 'cloudflare:workers';
import {currentAccount} from '@/lib/accounts';
export class HttpError extends Error { constructor(public status:number,message:string){super(message)} }
export function db(){if(!env.DB)throw new HttpError(503,'Project storage is unavailable. Please try again later.');return env.DB}
export async function owner(request?:Request){const user=await currentAccount();if(!user)throw new HttpError(401,'Sign in to your private workspace before saving a project.');if(request&&request.method!=='GET'){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)throw new HttpError(403,'This request must come from your workspace.')}return user.id}
export async function body(request:Request){if(Number(request.headers.get('content-length')||0)>12000)throw new HttpError(413,'The request is too large.');const raw=await request.text();if(raw.length>12000)throw new HttpError(413,'The request is too large.');try{return JSON.parse(raw)}catch{throw new HttpError(400,'Invalid request body.')}}
export function textValue(value:unknown,max=160){if(typeof value!=='string'||!value.trim()||value.length>max)throw new HttpError(400,'Please provide valid project details.');return value.trim()}
export async function ownedProject(id:string,user:string){const p=await db().prepare('SELECT * FROM projects WHERE id = ? AND owner = ?').bind(id,user).first<any>();if(!p)throw new HttpError(404,'Project not found.');return p}
export function fail(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});console.error('Workspace operation failed',error instanceof Error?error.message:'Unknown error');return Response.json({error:'This operation could not be completed. Your existing data is safe. Please try again.'},{status:500})}
