'use client';
import {useEffect,useState} from 'react';
import '../account-design.css';
import '../dashboard/pages.css';
export default function ResetPassword(){
 const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{setToken(window.location.hash.slice(1));history.replaceState(null,'','/reset-password')},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setError('');setMessage('');if(token&&data.get('password')!==data.get('confirm')){setError('Passwords do not match.');return}setBusy(true);try{const r=await fetch('/api/password-reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{action:'reset',token,password:data.get('password')}:{action:'request',email:data.get('email')})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);if(token)setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="account-page account-settings"><a className="suite-brand" href="/">GrowthPilot</a><section className="account-card"><h1>{token?'Set a new password':'Forgot your password?'}</h1><p>{token?'Choose a password with 12–128 characters.':'We’ll email you a link to reset your password.'}</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!done&&<form className="account-form" onSubmit={submit}>{token?<><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label></>:<label>Email address<input name="email" type="email" autoComplete="email" maxLength={254} required/></label>}<button className="suite-primary" disabled={busy}>{busy?'Please wait…':token?'Reset password':'Email me a reset link'}</button></form>}<p><a href="/account">Back to sign in</a></p></section></main>;
}
