'use client';
import {useState} from 'react';
import {categories,scoreValue,KpiTile,TickGauge,BarChart} from './scores';
export default function DashboardOverview({project,audit,busy,onRun,onView,openActions}:{project:{name:string,url:string},audit:any,busy:boolean,onRun:()=>void,onView:()=>void,openActions:number}){
 const [device,setDevice]=useState<'mobile'|'desktop'>('mobile');const report=audit?.performance?.[device];const values=categories.map(([id,label])=>({label,score:report?.status==='available'?scoreValue(report.categories?.find((c:any)=>c.id===id)?.score??(id==='performance'?report.score:null)):null}));const performance=values[3].score;
 const shot=(d:string)=>{const s=audit?.performance?.[d]?.screenshot;return typeof s==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s)?s:null};
 const images=new Set((audit?.pages||[]).flatMap((p:any)=>p.imageUrls||[]));
 return <><div className="db-kpis">{values.map(v=><KpiTile key={v.label} {...v} device={device}/>)}</div><div className="db-main-grid"><section className="db-card db-audit"><div className="db-card-head"><div><h2>Audit results</h2><p>{project.name} · <a href={project.url} target="_blank" rel="noreferrer">{new URL(project.url).hostname} ↗</a></p></div><div className="db-controls">{(['mobile','desktop'] as const).map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='mobile'?'Mobile':'Desktop'}</button>)}<button disabled={!audit} onClick={onView}>View full report →</button></div></div><div className="db-hero"><div className="db-previews"><div className="db-desktop"><div className="db-browser">● ● ●　{new URL(project.url).hostname}</div>{shot('desktop')?<img src={shot('desktop')!} alt="Desktop website preview"/>:<div className="db-placeholder">No desktop screenshot</div>}</div><div className="db-phone">{shot('mobile')?<img src={shot('mobile')!} alt="Mobile website preview"/>:<div className="db-placeholder">No mobile screenshot</div>}</div></div><div className="db-verdict"><span className="db-status">{performance===null?'Awaiting measurement':performance>=90?'Good performance':'Needs attention'}</span><h3>{performance===null?'Run an audit to measure this site.':`${device==='mobile'?'Mobile':'Desktop'} performance scores ${performance}${performance<90?' — there is room to improve.':'.'}`}</h3><p>{report?.status==='unavailable'?report.reason:'Review the saved measurements and page findings to plan your next improvements.'}</p><button disabled={!audit} onClick={onView}>Review {audit?.issues.length??0} HTML issue categories →</button></div></div><div className="db-audit-stats">{[['Pages checked',audit?.pages.length??0],['HTML issue categories',audit?.issues.length??0],['Open actions',openActions],['Unique images',images.size]].map(([label,value],i)=><div key={label} style={{borderBottomColor:['#3068f6','#ff9100','#0cba70','#8056ff'][i]}}><strong>{value}</strong><small>{label}</small></div>)}</div><p className="db-caption">{audit?.coverage||'No audit yet'} · Lighthouse scores test the entry URL and are not an overall website grade.</p><button disabled={busy} onClick={onRun}>{busy?'Auditing…':'Run audit'}</button></section><div className="db-side-stack"><section className="db-card db-gauge"><h2>{device==='mobile'?'Mobile':'Desktop'} performance</h2><TickGauge score={performance}/><button disabled={!audit} onClick={onView}>Show details</button></section><section className="db-card"><div className="db-card-head"><h2>Scores by category</h2><small>{device}</small></div><BarChart values={values}/></section></div></div></>
}
